### ISSUE TITLE
Question: next release!?

### ISSUE THREAD

**Issue by alecstheone** [Novalys/PokemonGo-Bot-SimpleGUI#101]
When will be the next release that will also fix the bot from crashing?

Thanks!

**Comment by Novalys** [comment]
Hopefully tomorrow :smile: ! I have a day time job (also as a programmer) so its hard to find spare time in the evening to work on this.. but tomorrow it seems like I'll have some free time to fully work on this!

**Comment by alecstheone** [comment]
Ok. Thank you alot and congratulations again for this piece of software!
