### ISSUE TITLE
Unable to manually choose lat/long

### ISSUE THREAD

**Issue by chromeplatedhrt** [Novalys/PokemonGo-Bot-SimpleGUI#105]
Using master with VS2015. I can choose "best places" or the default, but it will not take manually entered lat/long.

**Comment by Novalys** [comment]
Thanks for the report, I'll check this out!

**Comment by chromeplatedhrt** [comment]
@Novalys Are we able to manually input lat/long in new release?

**Comment by Sbrown-WilliamsCrusher** [comment]
I will not take the manually entered ones. I tried on the v1 just now. Would like if it did so I lessen chance of ban. But all in all great job with the program!

**Comment by Delko0** [comment]
I just tried,maunally setting location will not work

**Comment by Novalys** [comment]
This is solved in the latest release. https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/releases/latest
