### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by darkhax** [Novalys/PokemonGo-Bot-SimpleGUI#107]
Would it be possible to have this app support Linux as well? It partially works with wine however authentication fails.

**Comment by brutang** [comment]
Yeah I tried it with wine as well. I think it's a networking issue with
wine.

**Comment by Novalys** [comment]
This is indeed possible, I suggest to try and compile the solution with Mono. I don't see why it shouldn't work but I don't have enough time to maintain this version for Windows to add support for Mac OS or Linux :cry:
