### ISSUE TITLE
I dont see the .exe file

### ISSUE THREAD

**Issue by Vortonic** [Novalys/PokemonGo-Bot-SimpleGUI#108]
Where is it located?

**Comment by smholsen** [comment]
Have you cloned the repo or downloaded a release?

**Comment by adamgyongyosi** [comment]
https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/releases

**Comment by Vortonic** [comment]
Thanks got it

**Comment by Novalys** [comment]
Please check the [Latest Release](https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/releases/latest).
