### ISSUE TITLE
strat app clean log

### ISSUE THREAD

**Issue by adamgyongyosi** [Novalys/PokemonGo-Bot-SimpleGUI#109]
if i start app clean log.txt or create backup with x h

 and i need scroll bar

http://imgur.com/GvDvaa7

**Comment by Novalys** [comment]
Please check the [Latest Release](https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/releases/latest). The log window is separated from the main GUI so you can view more information there, thanks!
