### ISSUE TITLE
Option to not evolve pokemons (Suggestion)

### ISSUE THREAD

**Issue by smholsen** [Novalys/PokemonGo-Bot-SimpleGUI#111]
I would like a checkbox with option to not evolve any pokemons.

I can address this at the weekend :) 

(I dont have time to check it out until the weekend, but for a quick solution maybe just add a checkbox to the mainView and in the method where pokemons to evolve is added to the pokemonToEvolve list, just do an if check of the checkbox and if checked, then just dont add any pokemons) ?

**Comment by Novalys** [comment]
Please check the [Latest Release](https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/releases/latest). This is available in the settings view. Thanks!
