### ISSUE TITLE
[Feature] Login Remember me?

### ISSUE THREAD

**Issue by adamgyongyosi** [Novalys/PokemonGo-Bot-SimpleGUI#112]
can you add remember me action for auth?

**Comment by Novalys** [comment]
Let's see if there is enough interest about this feature.

**Comment by lgromb** [comment]
I would second that.

**Comment by Sbrown-WilliamsCrusher** [comment]
:+1:

**Comment by ryandailey100** [comment]
Would be a great feature

**Comment by Novalys** [comment]
OK OK! I get it, adding this... :smile: should be ready for v1.2

**Comment by adamgyongyosi** [comment]
@Novalys its working, i close
