### ISSUE TITLE
Feature Questions/Suggestions

### ISSUE THREAD

**Issue by chromeplatedhrt** [Novalys/PokemonGo-Bot-SimpleGUI#114]
1. Is there a way to farm Pokes only without having Pokestops nearby? 
2. Can we turn off transfer & evolve so it does not do it when it reaches the last stop? 
3. Can we manually choose what to transfer, evolve, and recycle?

**Comment by Novalys** [comment]
Please check the [Latest Release](https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/releases/latest). You can all those things now, thanks!
