### ISSUE TITLE
Suggestions to help on the perfect IV hunt

### ISSUE THREAD

**Issue by VincePrinceKing** [Novalys/PokemonGo-Bot-SimpleGUI#116]
Once you reach the mid 20s, or higher of your Trainerlevel, most of the game-play revolves around getting the best IV Pokemon, evolving it and hoping it gets the attacks you want and if not trashing it most of the time. As you should have saved tons of Stardust and plenty candy the main part becomes finding the Pokemon with the most fitting stats (IVs). 

To help all hunters that want the best Pokemon here some suggestions:

1. "print" out IV's of all Pokemon
If the bot could read out all the IVs and give them out in a .txt or something like that (sorted by %) that could help much, especially since the bot can get the real values of attack/defense/stamina and doesn't have to guess inside a range, like you if you check IVs. You often have to invest candy+stardust to see if its a valuable 98% or just another crappy 60% eevvee.

2. "prioritize the IV over CP when catching/transferring" mode, 
or option to set other IV min value than the default 85. For rare but high value Pokemon like Dratini you probably want any IV as high as you will get them. Even if you cant get over the magic 85. Right now the Dratini of a IV of 80% with low CP will get deleted if for example a useless IV 10% Dratini of high level appears. And that is just plain crap and not worth any further investment.

**Comment by Novalys** [comment]
Please check the "My Pokemon" option in the latest release, it does in part what you are looking for. Let me know what you think.

**Comment by VincePrinceKing** [comment]
I really like it so far, its going in the right direction. Here is what could improve it even further:

1.It takes forever to load the full List (got arround170 Pokemon for reference). For every 4 new Pokemon in the list it takes around 5 seconds. Once fully loaded the reloads if i close and then klick "my pokemon" are fast.

2. The List seems unsorted?To make it more accessible, sort it by "Pokemon Nr #" first and for the same # in descending IV to make it easy to search through and use. ( Pokemon Nr #>IV>CP seem most useful, but you could also consider name and CP and Name, (Name>CP>IV))

3. For my >150 Pokemon the list quite long to scroll down. If you would make the list bigger (show more Pokemon at a time) that could also improve the handling. I guess like one more row and one more column could already help much.

4. More of a question. Why the "Automatically Evolve/Transfer Pokemon..." Trigger grouped together and not just two separate ones? I for example might have use for the auto transfer one. But i don't want some random/low IV Dratini/Magicarp evolution waste my precious rare Candy.

5. Carrying on the previous thought. Perfect would be and Auto evolve that only auto evolves if you already posses candy above an custom set candy Value of the affected candy. Around 175 for every Pokemon (with exception of Magicarp/Gyarados there 175+275=450) That way you could have enough candy to level and evolve your high IV Pokemon once you catch it, but still can profit of the bonus exp of auto evolving.


anyway keep up the good work, you're truly our hero.
