### ISSUE TITLE
pokemongo.rocketapi.gui has stopped working 

### ISSUE THREAD

**Issue by taran1995** [Novalys/PokemonGo-Bot-SimpleGUI#118]
after i dl the latest release, i click the google login. it pop up a google website and the program stop working.

**Comment by Novalys** [comment]
Yeah, I'm going to remove the clipboard function. I'll get back to you when the fix is uploaded.

**Comment by adzcsx2** [comment]
thanks`

**Comment by okiprasetya** [comment]
i got same problem :( please help

**Comment by Novalys** [comment]
Yeah, I disabled the clipboard but the problem right now is with Google Login.. NecroBot is also having the same problem.

**Comment by Novalys** [comment]
Let's use issue #92 for this problem.
