### ISSUE TITLE
good tip

### ISSUE THREAD

**Issue by adamgyongyosi** [Novalys/PokemonGo-Bot-SimpleGUI#119]
- convert seconds into (Hour:Minutes:Seconds) time

info: http://stackoverflow.com/a/463668

- pls add change function  map loc if i stop botting (find place, set lat,lng, select good place)
- show lat, lng coords ( i cant see )
- show use item(s) time remaining

**Comment by Novalys** [comment]
Thanks! Will add this on the next release.
