### ISSUE TITLE
[BUG] used incence

### ISSUE THREAD

**Issue by adamgyongyosi** [Novalys/PokemonGo-Bot-SimpleGUI#120]
![image](https://cloud.githubusercontent.com/assets/5511526/17202354/17680a8c-5499-11e6-8694-5a00886f398a.png)

and not used

**Comment by Novalys** [comment]
That's really odd if you press start farming it doesn't refresh? if you used while the bot is stopped it doesn't refresh.

**Comment by Novalys** [comment]
Never mind, I was able to reproduce the problem. Let me investigate.

**Comment by adamgyongyosi** [comment]
@Novalys oke thx
