### ISSUE TITLE
Google Login is not Working [Still Looking for a Fix]

### ISSUE THREAD

**Issue by jawak** [Novalys/PokemonGo-Bot-SimpleGUI#121]
![go](https://cloud.githubusercontent.com/assets/9127068/17203915/711c7ee0-54cc-11e6-8861-452f83f22ca8.png)

**Comment by adamgyongyosi** [comment]
![image](https://cloud.githubusercontent.com/assets/5511526/17203972/f4c2d8fe-54a2-11e6-8067-e1be8e31b68b.png)

**Comment by c00lerm4n** [comment]
the same for me :(
![error](https://cloud.githubusercontent.com/assets/20622515/17204094/9d63bc2e-54cd-11e6-8d85-58f1746b0178.png)

**Comment by Novalys** [comment]
Guys there is currently a problem with Google Login Servers, we'll need to wait until tomorrow to see if they solve this or if we need to do it on our side.

**Comment by s84088722** [comment]
me too

**Comment by dowit** [comment]
Yes confirmed working in the old version but on the new i got the error msg "Unable to authenticate with login server"

**Comment by benbull** [comment]
Same here, old version works fine, as does compiled version from 12 hours a go.  Using Google login, same account on different versions.  This is definitely client side.

**Comment by Dbarr74** [comment]
The old was working for me, but stopped about 10-15 minutes ago, now giving me the same error when logging in.

**Comment by Novalys** [comment]
It's not client side, well I mean it is.. the problem is with the tokens provided by Google are not longer being accepted by the server, I already tried creating new tokens with my own credentials but it's the same error, if older versions are working for you it's because they have a token that is still valid.

**Comment by The-Hasanov** [comment]
@Novalys how login username password ?

**Comment by heas2-07** [comment]
So the dreams over?

**Comment by benbull** [comment]
@Novalys I noticed you changed the ClientID and ClientSecret in ac02401 commit within GoogleLogin.cs - would this cause this bug?

**Comment by Novalys** [comment]
@benbull yeah when people started experiencing this problem I thought it could be a credentials problem but it wasn't, right now some people are claiming they are able to login fine while some others still have the problem, best is to wait until tomorrow before making changes.

**Comment by Dbarr74** [comment]
error message up on pokevision about the server too, so yea, going to say probably an issue with the server.

**Comment by benbull** [comment]
@Dbarr74 http://ispokemongodownornot.com/

**Comment by adamgyongyosi** [comment]
how to try a new google keys?

**Comment by laernumoretz** [comment]
Looking for where to change the google login personally, made a new folder and download and its pulling my google user name still from god knows where :0. Only the login button showing no fields

**Comment by neetkee** [comment]
It works againg.

**Comment by dowit** [comment]
still not working, anyway to use the old token with this version?

**Comment by benbull** [comment]
@neetkee @dowit Important distinction, it's working for Pokemon Trainer Club accounts, but not working for Google Accounts.

**Comment by neetkee** [comment]
@benbull I'm currently able to login with Google Account. Did nothing with code.

**Comment by benbull** [comment]
@neetkee Really?  I can't get it to launch with Google Account, are you compiling from source or just running the latest release?  Have you altered anything?

**Comment by neetkee** [comment]
@benbull I'm compiling from source. Tried to login about an hour ago, it wasn't work. Attempt now to reset token, but can't get device code.

**Comment by neetkee** [comment]
Can't get new token. Authentication not working. You can read more here: https://github.com/NecronomiconCoding/NecroBot/issues/1169

**Comment by dowit** [comment]
@Novalys  where the google token is stored on the new version? anyway to put it in the code directly?

**Comment by Silenieux** [comment]
happens to me with the new launcher as well, can fix it manually if i can find the token

**Comment by derohimat** [comment]
still problem in version 1.0

**Comment by benbull** [comment]
@Silenieux The tokens are stored in %USER%\AppData\Local\PokemonGo

**Comment by Silenieux** [comment]
@benbull yep, was able to find it, i transfered the old login token to the new token folder created by the new version and i was able to get it to log in without crashing, it should help some folks temporarily if they used a previous version, ofr they can probably use a previous version to setup the token, then copy it over

**Comment by hsizadam** [comment]
i dont know about this things so excuese me if this is a stupid idea :)

i have a pokemap desktop api and i can log in with my google account on that. it is not asking for any token or sth. is there anyway that we can do that for bot?

**Comment by The-Hasanov** [comment]
login by token
[GoBot](https://github.com/Panthere/GoBot)

**Comment by Novalys** [comment]
It's working now in version 1.1, the authentication system was changed to use Google Credentials which should be easier. Open a new issue if you guys still have problems.
