### ISSUE TITLE
Suggestion : Updates within the app ? All windows opened at once ?

### ISSUE THREAD

**Issue by lgromb** [Novalys/PokemonGo-Bot-SimpleGUI#122]
Hi,

Why not try to implement automatic updates ? (or at least notifications ?), and can we have the ability to open Console, Status windows and everything within the program without locking it ? (The presence of a button in a child-opened window make the main window non clickable)

Thanks ! #

**Comment by Novalys** [comment]
Could expand on automatic updates? You mean like opening the application and automatically receive the latest updates?

**Comment by lgromb** [comment]
Yeah, maybe people not like me won't check that repo everytime they're online. I was just thinking of some sort of tiny button flashing when there is a new release avaliable here you see the point ?

**Comment by adamgyongyosi** [comment]
@Novalys it is good idea because not all time check a new released

**Comment by Novalys** [comment]
A custom update process will be set up in the near future, thanks!
