### ISSUE TITLE
Cant login via PTC

### ISSUE THREAD

**Issue by c00lerm4n** [Novalys/PokemonGo-Bot-SimpleGUI#124]
I was going to login via ptc, but this happened.
What should I do?
![error ptc](https://cloud.githubusercontent.com/assets/20622515/17208175/97b8da7a-54e1-11e6-9010-c464d2c3cac3.png)

**Comment by benbull** [comment]
PTC is down; http://ispokemongodownornot.com/

**Comment by c00lerm4n** [comment]
Thank you very much! :D

**Comment by Sbrown-WilliamsCrusher** [comment]
@c00lerm4n Sadly pkmn can't keep their servers running. But looks like they are online now. Suggesting the closing of this ticket.
