### ISSUE TITLE
[SUGGESTION] Sniping pokemon

### ISSUE THREAD

**Issue by Delko0** [Novalys/PokemonGo-Bot-SimpleGUI#127]
Would it be possible to get the cords of lets say something rare like dragonite,and just put them in the app and it would grab him and go back to your location so you get no soft bans? Can this be added?

**Comment by Sbrown-WilliamsCrusher** [comment]
When the bug of being able to manually enter cords is fixed you could use pokevision and snipe them that way. Soft bans are not @Novalys fault its pogo trying to stop people from botting

**Comment by Delko0** [comment]
@Sbrown-WilliamsCrusher I've heard you can teleport and avoid them

**Comment by Sbrown-WilliamsCrusher** [comment]
Heres a good topic on soft-bans 
http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/562183-soft-bans-what-we-know-should-you-worried-how-avoid.html

**Comment by Novalys** [comment]
I had this idea where you can snipe by just copy/paste a pokevision URL like https://pokevision.com/#/@51.49546550322391,-0.08128166198730469 and it would automatically go to that location and start farming (should farm the pokemon you are looking for). This most likely cause a soft ban if you previous location was far away from that one, but... Still seems like it would work as long as  you are not too far away.

**Comment by Delko0** [comment]
@Novalys  http://pokesnipers.com/ i found this site , http://prntscr.com/byq031 and this method dunno if it can be implemented what do you think?

**Comment by Novalys** [comment]
Interesting, I will take a look at this to see if this is possible.

**Comment by chromeplatedhrt** [comment]
I think both of these ideas are awesome! Would love to see sniping abilities implemented!

**Comment by Delko0** [comment]
@Novalys  i tried sniping with your bot,but it just takes a zubat and moves away,would be pretty cool if we could choose to stick to one place,like a circle

**Comment by Novalys** [comment]
This is added now in version 1.5
