### ISSUE TITLE
<SUGGESTION> Farming priorities / Item prioirty

### ISSUE THREAD

**Issue by lordboltin** [Novalys/PokemonGo-Bot-SimpleGUI#128]
One feature I have not seen on any of the bots is the ability to prioritize what your bot is doing during its run.

At times it would be helpful to have the bot stock up on certain items or even be able to specify how many of each item you want in comparison to the size of the bag.

Thanks for all the effort!

Let me know if I can help with anything design related!

**Comment by Novalys** [comment]
The option to have a panel where you can define how many of each item to keep is coming very soon! Should be in the next release, thanks for the suggestion!
