### ISSUE TITLE
Version 1.0 Crash via Login Google

### ISSUE THREAD

**Issue by TheBlueSmile** [Novalys/PokemonGo-Bot-SimpleGUI#129]
Start Programm from Downloads lokation.
With and Without Admin.
Press Google and Login -> Website google open and programm crash

[DxDiag.txt](https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/files/388841/DxDiag.txt)

Problemsignatur:
  Problemereignisname:	CLR20r3
  Problemsignatur 01:	PoGoBot-GUI.exe
  Problemsignatur 02:	1.0.0.0
  Problemsignatur 03:	579988fd
  Problemsignatur 04:	System.Windows.Forms
  Problemsignatur 05:	4.0.30319.34250
  Problemsignatur 06:	54d46da6
  Problemsignatur 07:	13e2
  Problemsignatur 08:	12
  Problemsignatur 09:	System.ArgumentNullException
  Betriebsystemversion:	6.3.9600.2.0.0.256.48
  Gebietsschema-ID:	1031
  Zusatzinformation 1:	5861
  Zusatzinformation 2:	5861822e1919d7c014bbb064c64908b2
  Zusatzinformation 3:	1318
  Zusatzinformation 4:	13181ae637ac2592fac0ca2dd662cdcc

**Comment by vsoraas** [comment]
Same.

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	PoGoBot-GUI.exe
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	579988fd
  Problem Signature 04:	System.Windows.Forms
  Problem Signature 05:	4.6.1055.0
  Problem Signature 06:	563c0fe8
  Problem Signature 07:	971
  Problem Signature 08:	12
  Problem Signature 09:	System.ArgumentNullException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by Silenieux** [comment]
There's already a large thread on it.  Which version are you using, i was able to transfer the token from .11 to 1.0 to get it to work again.

**Comment by vsoraas** [comment]
Which version of the bot, you mean? The latest release, downloaded just about 10 minutes ago.

**Comment by Novalys** [comment]
This is fixed in the latest release, please try that one out and open a new ticket if you still have this problem! Thanks!
