### ISSUE TITLE
V1.0 Vs .11 catching pokemon (info inside)

### ISSUE THREAD

**Issue by Silenieux** [Novalys/PokemonGo-Bot-SimpleGUI#131]
i've been testing 1.0 vs .11 and i've noticed in .11 i had a high catch rate of pokemon (90%) where as with 1.00 i seem to only have a catch rate of 20-30% of encountered pokemon. At first I thought i was soft banned but then it caught one and continued to lose the next 5-6 pokemon

**Comment by Novalys** [comment]
In version 1.0+ you can change the delays in the settings, if you set the delays to 10 seconds for Pokestop and Pokemon you'll get the 90% rate, try tweaking those numbers until you find the sweet spot for you. Thanks!
