### ISSUE TITLE
[SUGGESTION] New location/Custom Locations

### ISSUE THREAD

**Issue by Zevenx** [Novalys/PokemonGo-Bot-SimpleGUI#132]
Hi, first I need to say Thanks a lot for this app, this is so cool.
Secondly I really want to add a custom locations to this app, its "Disneyland Park (33.8120962,-117.9189742) ", because it have a lot of PokeStops and its really easy to farm items just like pokeballs and potions.

Sorry if my english is Bad, I´m native spanish

**Comment by Novalys** [comment]
Muchas gracias, ya la agregue a la lista :wink:
