### ISSUE TITLE
V1.1 Google login

### ISSUE THREAD

**Issue by c00lerm4n** [Novalys/PokemonGo-Bot-SimpleGUI#134]
This happened while logging in via google with the newest version. any solution?
Thanks :D
![error](https://cloud.githubusercontent.com/assets/20622515/17222931/a7881810-5524-11e6-9f85-ceee502b182c.png)

**Comment by Novalys** [comment]
That means the servers are unresponsive, just give it sometime and it will connect. Once the servers are 100% you won't have this problem and it will connect instantly.
