### ISSUE TITLE
Stardust Count 

### ISSUE THREAD

**Issue by maurxians023** [Novalys/PokemonGo-Bot-SimpleGUI#136]
please input total stardust count thanks

**Comment by maurxians023** [comment]
is this working now on 1.4V?

**Comment by Novalys** [comment]
No, this is pending, will be added in the next release! Thanks.

**Comment by maurxians023** [comment]
Sir, are you still working to update the stardust? :+1:

**Comment by maurxians023** [comment]
sir im willing to send some donation but please help me with stardust. 

your program is suitable for me. and its easy to manage than other bot
