### ISSUE TITLE
Google Login not working (2FA)

### ISSUE THREAD

**Issue by vsoraas** [Novalys/PokemonGo-Bot-SimpleGUI#137]
(Console)
Adjusting the Settings.
Trying to Login with Google Token.
Unable to Connect using the Google Token.
(MsgBox) 
Unable to Authenticate with Login Server.

Am I supposed to have a separate password for this, in some way? Using the normal password, as well as username, or username@gmail.com generates this error.

**Comment by adamgyongyosi** [comment]
![image](https://cloud.githubusercontent.com/assets/5511526/17224135/ecb69620-54ff-11e6-843f-560d4160f02f.png)

**Comment by UncleMart** [comment]
Have you guys tried using the clear token option?

**Comment by adamgyongyosi** [comment]
%USER%\AppData\Local\PokemonGo

**Comment by Novalys** [comment]
That's the error you get when you enter incorrect credentials, it should be youremail@gmail.com / yourgmailpassword is that how you are trying to login?

**Comment by vsoraas** [comment]
Yeah, I tried both with and without the @gmail.com. Haven't tried the token thing UncleMart mentioned.

**Comment by Esenlikoglu** [comment]
the executable version still doesn't work with Google login (mymail@gmail.com + Password)
I cleared the old tokens from the Appdata, downloaded the executable version again, but it still doesnt work. 

![error](https://cloud.githubusercontent.com/assets/20710608/17226713/fd26220e-550a-11e6-8528-537268979fde.jpg)

Running the SLN files with Visual Studio is stable.

**Comment by UncleMart** [comment]
Novalys, could the servers being down return this error?

here's a useful page to check if anyone is having login probs (today has been pretty bad too) https://go.jooas.com

**Comment by Esenlikoglu** [comment]
I think its a client issue, since he tries to log in with a "TOKEN" where I don't have a token (yet). Usually u get the 8 digit code and IE pops up for verification and create the token.

**Comment by Moolaned** [comment]
For everyone who has this problem (people with 2FA), please go to https://security.google.com/settings/security/apppasswords and generate an app password for bot. 

@Novalys , please add link to generate password. I believe this issue can be closed.

**Comment by fcnrk** [comment]
Hi, I've experienced a similar problem with Google login. But this time, the post request made to "https://accounts.google.com/o/oauth2/device/code" to obtain a device code returned a 401 unauthorized error. Any ideas?

**Comment by adamgyongyosi** [comment]
#175 solved
