### ISSUE TITLE
Select what pokemon not to evolve

### ISSUE THREAD

**Issue by Dbarr74** [Novalys/PokemonGo-Bot-SimpleGUI#139]
Just an idea, I'd like if we could select types of pokemon to not evolve, I myself would rather save bulbasaur, squirtle, charmander and Dratini candy for the high IV ones instead of the bot just selecting the ones to evolve.

Just thought it'd be a big improvement, unless you can do this already and I'm not seeing how.

**Comment by Markmanus** [comment]
Yeah that would be great. Also about evolving...i had a 157cp magikarp and had enough candy to evolve...but instead, it randomly evolved a 25 cp magkarp so i got a 256 cp gyarados instead of a 1600+.

That could be an issue if somebody start using the bot with saved candy/good cp pokemon.
