### ISSUE TITLE
Unable to download or execute .exe

### ISSUE THREAD

**Issue by netherkingblaze** [Novalys/PokemonGo-Bot-SimpleGUI#140]
I am unable to download or execute the file without my anti-virus going off however when I attempt to run a previous version it runs without problems. Has there been any change in code to make this be recognized by anti-virus as a malicious program.

**Comment by philbritton** [comment]
yea I'm getting a MSILPerseus.42898 alert from IObit Malware Fighter

**Comment by Versified** [comment]
Well, just add the .exe as an exception or just disable your antivirus temp.
