### ISSUE TITLE
A lot of Run Aways

### ISSUE THREAD

**Issue by chromeplatedhrt** [Novalys/PokemonGo-Bot-SimpleGUI#143]
Using latest release. I have encountered 12 pokes, and caught 5. So over half are runaways. Only a lvl 14 on this acct. Any ideas?

**Comment by AliAlhabib** [comment]
if the runaways are sequenced you could have been softbanned, but most likely it's just normal. you caught anymore pokemons after the runaways? did you move across the map without caution?

**Comment by chromeplatedhrt** [comment]
I am catching some, then getting a few runaways, then capturing a couple. But I am getting items from all the stops. I am pretty sure it isn't a soft ban.

**Comment by chromeplatedhrt** [comment]
Here is an example... 

![capture](https://cloud.githubusercontent.com/assets/20599857/17228047/5e67bb8a-54df-11e6-8cbd-2a63fe9fcefc.JPG)

**Comment by AliAlhabib** [comment]
I understand, sometimes it happens to me as well, you can always mess with which pokeballs to use against what CPs if you want in Mainform.cs

**Comment by Silenieux** [comment]
@chromeplatedhrt  change your delay between pokemon to 12 seconds worked for me

**Comment by chromeplatedhrt** [comment]
@Silenieux Did you change it to 12 for both stops and pokes?
