### ISSUE TITLE
Feature request : Egg hatching ?

### ISSUE THREAD

**Issue by lgromb** [Novalys/PokemonGo-Bot-SimpleGUI#144]
Hi again,

I really don't know how the API works but I was wondering if by any chance there was a way to implement egg hatching process by sending API calls from fake gyroscope or something ? (The perks of talking about something you really don't know about haha)

**Comment by dtmcode** [comment]
+1 would like to see this.

**Comment by Moolaned** [comment]
You can turn off GPS on your phone and manually load the eggs - thats what I have been doing. But an automated process would be nice. The bot does contribute to egg hatching. There is no need to fake the data.

**Comment by Novalys** [comment]
This is already in the works, thanks! :)
