### ISSUE TITLE
InvalidResponseException

### ISSUE THREAD

**Issue by vsoraas** [Novalys/PokemonGo-Bot-SimpleGUI#145]
![pogo-invalidresponseexception](https://cloud.githubusercontent.com/assets/693091/17230006/6dbaa800-551a-11e6-8f7e-4ae015e790c8.png)

Might be a problem with the Robot API, because I get the same behavior in a different bot based on Robot as well.

**Comment by dtmcode** [comment]
Problem with the pokemon go servers. Been running the latest build all day, only has errors when the pokemon go servers are overloaded.

**Comment by sayiid** [comment]
Same here. Not working. :(

**Comment by yupdon** [comment]
#157 has a hotfix

**Comment by nxy** [comment]
#164 Fix
