### ISSUE TITLE
Login looping and nothing happening

### ISSUE THREAD

**Issue by ErolTR** [Novalys/PokemonGo-Bot-SimpleGUI#149]
Once I login and select location, I get a error window saying "Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.

Then my console keeps looping this:

[17:56:16] Select Starting Location...
[17:56:19] Starting in Location Lat: 43.639274 Lng: -79.381006
[17:57:10] Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
[17:57:21] Items in Bag: 151/350.
[17:57:21] Lucky Eggs in Bag: 2
[17:57:21] Pokemons in Bag: 86/250.
[17:57:21] Inventory and Pokemon Space, Ready.
[17:57:22] ------------> InvalidReponseException
[17:57:22] <------------ Recovering
[17:57:22] Adjusting the Settings.
[17:57:22] Trying to Login with Google Token...
[17:57:22] Connected! Server is Ready.
[17:57:22] Attempting to Retrieve Inventory and Player Profile...
[17:57:22] Ready to Work.
[17:57:23] ------------> InvalidReponseException
[17:57:23] <------------ Recovering
[17:57:23] Adjusting the Settings.
[17:57:23] Trying to Login with Google Token...
[17:57:23] Connected! Server is Ready.
[17:57:23] Attempting to Retrieve Inventory and Player Profile...
[17:57:23] Ready to Work.
[17:57:24] ------------> InvalidReponseException
[17:57:24] <------------ Recovering
[17:57:24] Adjusting the Settings.
[17:57:24] Trying to Login with Google Token...
[17:57:25] Connected! Server is Ready.
[17:57:25] Attempting to Retrieve Inventory and Player Profile...
[17:57:25] Ready to Work.
[17:57:25] ------------> InvalidReponseException
[17:57:25] <------------ Recovering

**Comment by sayiid** [comment]
Same. Not working :(

**Comment by Silenieux** [comment]
same here, just started out of no where.

**Comment by SamuriBakePie** [comment]
After reviewing the discord it seems Niantic has upgraded their API

**Comment by zigbol** [comment]
The same is happening to me and i don't know what to do.

**Comment by sayiid** [comment]
maybe fix next day. i hope.

**Comment by KortakNL** [comment]
none of my bots are working...phone i log in fine..

whats going on...Niantic changed something?

**Comment by zigbol** [comment]
not that i know

**Comment by SamuriBakePie** [comment]
if you come into discord there is a temporary fix

**Comment by dtmcode** [comment]
Temp fix by Mulch here: https://github.com/dtmcode/PokemonGo-Bot-SimpleGUI

**Comment by nxy** [comment]
PokemonGo.RocketAPI.GUI\MainForm.cs
   
        private async Task ExecuteFarmingPokestopsAndPokemons()
        {
            var mapObjects = await _client.GetMapObjects();

            var pokeStops = mapObjects.MapCells.SelectMany(i => i.Forts).Where(i => i.Type == FortType.Checkpoint && i.CooldownCompleteTimestampMs < DateTime.UtcNow.ToUnixTime());

            var fortDatas = pokeStops as IList<FortData> ?? pokeStops.ToList();
            _pokestopsCount = fortDatas.Count<FortData>();
            int count = 1;

            foreach (var pokeStop in fortDatas)
            {
                var update = await _client.UpdatePlayerLocation(pokeStop.Latitude, pokeStop.Longitude, _settings.DefaultAltitude); // Redundant?
                UpdateMap(pokeStop.Latitude, pokeStop.Longitude);
                var fortInfo = await _client.GetFort(pokeStop.Id, pokeStop.Latitude, pokeStop.Longitude);

                boxPokestopName.Text = fortInfo.Name;
                boxPokestopInit.Text = count.ToString();
                boxPokestopCount.Text = _pokestopsCount.ToString();
                count++;                               

				await Task.Delay(2000);
                var fortSearch = await _client.SearchFort(pokeStop.Id, pokeStop.Latitude, pokeStop.Longitude);
                Logger.Write($"Loot -> Gems: { fortSearch.GemsAwarded}, Eggs: {fortSearch.PokemonDataEgg} Items: {StringUtils.GetSummedFriendlyNameOfItemAwardList(fortSearch.ItemsAwarded)}");
                Logger.Write("Gained " + fortSearch.ExperienceAwarded + " XP.");

                // Experience Counter
                _totalExperience += fortSearch.ExperienceAwarded;

                await GetCurrentPlayerInformation();
                Logger.Write("Attempting to Capture Nearby Pokemons.");
				await Task.Delay(2000);
                await ExecuteCatchAllNearbyPokemons();

                if (!_isFarmingActive)
                {
                    Logger.Write("Stopping Farming Pokestops.");
                    return;
                }                    

                Logger.Write("Waiting before moving to the next Pokestop.");
                await Task.Delay(GUISettings.Default.pokestopDelay * 1000);
            }}

AND

        private async Task ExecuteCatchAllNearbyPokemons()
        {
            var mapObjects = await _client.GetMapObjects();

            var pokemons = mapObjects.MapCells.SelectMany(i => i.CatchablePokemons);

            var mapPokemons = pokemons as IList<MapPokemon> ?? pokemons.ToList();
            Logger.Write("Found " + mapPokemons.Count<MapPokemon>() + " Pokemons in the area.");
            foreach (var pokemon in mapPokemons)
            {   
                var update = await _client.UpdatePlayerLocation(pokemon.Latitude, pokemon.Longitude, _settings.DefaultAltitude); // Redundant?
                var encounterPokemonResponse = await _client.EncounterPokemon(pokemon.EncounterId, pokemon.SpawnpointId);
                var pokemonCp = encounterPokemonResponse?.WildPokemon?.PokemonData?.Cp;
                var pokemonIv = Logic.Logic.CalculatePokemonPerfection(encounterPokemonResponse?.WildPokemon?.PokemonData).ToString("0.00") + "%";
				await Task.Delay(2000);
                var pokeball = await GetBestBall(pokemonCp);

                Logger.Write($"Fighting {pokemon.PokemonId} with Capture Probability of {(encounterPokemonResponse?.CaptureProbability.CaptureProbability_.First())*100:0.0}%");

                boxPokemonName.Text = pokemon.PokemonId.ToString();
                boxPokemonCaughtProb.Text = (encounterPokemonResponse?.CaptureProbability.CaptureProbability_.First() * 100).ToString() + @"%";                

                CatchPokemonResponse caughtPokemonResponse;
                do
                {
                    if (encounterPokemonResponse?.CaptureProbability.CaptureProbability_.First() < (GUISettings.Default.minBerry / 100))
                    {
					    await Task.Delay(2000);
                        await UseBerry(pokemon.EncounterId, pokemon.SpawnpointId);
                    }

					await Task.Delay(2000);
                    caughtPokemonResponse = await _client.CatchPokemon(pokemon.EncounterId, pokemon.SpawnpointId, pokemon.Latitude, pokemon.Longitude, pokeball);
                    await Task.Delay(2000);
                }
                while (caughtPokemonResponse.Status == CatchPokemonResponse.Types.CatchStatus.CatchMissed);

                Logger.Write(caughtPokemonResponse.Status == CatchPokemonResponse.Types.CatchStatus.CatchSuccess ? $"We caught a {pokemon.PokemonId} with CP {encounterPokemonResponse?.WildPokemon?.PokemonData?.Cp} using a {pokeball}" : $"{pokemon.PokemonId} with CP {encounterPokemonResponse?.WildPokemon?.PokemonData?.Cp} got away while using a {pokeball}..");

                if (caughtPokemonResponse.Status == CatchPokemonResponse.Types.CatchStatus.CatchSuccess)
                {
                    // Calculate Experience
                    int fightExperience = 0;
                    foreach (int exp in caughtPokemonResponse.Scores.Xp)
                        fightExperience += exp;
                    _totalExperience += fightExperience;
                    Logger.Write("Gained " + fightExperience + " XP.");
                    _pokemonCaughtCount++;

                    // Add Row to the DataGrid
                    dGrid.Rows.Insert(0, "Captured", pokemon.PokemonId.ToString(), encounterPokemonResponse?.WildPokemon?.PokemonData?.Cp, pokemonIv);
                }
                else
                {
                    // Add Row to the DataGrid
                    dGrid.Rows.Insert(0, "Ran Away", pokemon.PokemonId.ToString(), encounterPokemonResponse?.WildPokemon?.PokemonData?.Cp, pokemonIv);
                }

                boxPokemonName.Clear();
                boxPokemonCaughtProb.Clear();

                await GetCurrentPlayerInformation();

                if (!_isFarmingActive)
                {
                    Logger.Write("Stopping Farming Pokemons.");
                    return;
                }

                Logger.Write("Waiting before moving to the next Pokemon.");
                await Task.Delay(GUISettings.Default.pokemonDelay * 1000);
            }}

**Comment by nxy** [comment]
#164
