### ISSUE TITLE
Not catching any Pokemon / Only Pokestops + crashing after few minutes

### ISSUE THREAD

**Issue by maxepix** [Novalys/PokemonGo-Bot-SimpleGUI#150]
So after I've managed to create a app token with my gmail account,
It seems that it only goes for the Pokestops (not getting any xp/items out of 75% of them)
while it's not catching any pokemon at all.

Also it keeps on crashing after about 5-10 Minutes with "failed to authentificate with the server" or just something not working correctly anymore.

**Comment by BunyaminS** [comment]
Same issue has already been mentioned, this thread can be merged with #149 or be closed.

**Comment by maxepix** [comment]
Oh I'm sorry didn't see that in time.
