### ISSUE TITLE
Locations magikarp / dratini nests

### ISSUE THREAD

**Issue by yupdon** [Novalys/PokemonGo-Bot-SimpleGUI#154]
I'd add them myself, but I can't figure out pull / merge thing going .. so i'm just running these 2 locally.

- Netherlands, Amsterdam magikarp nest - https://pokevision.com/#/@52.373124,4.895865
- USA, Sacramento dratini nest -https://pokevision.com/#/@38.548232549872026,-121.23232841491698 
- USA, Tulsa,Zoo machop nest - https://pokevision.com/#/@36.210981,-95.908203
Code-

comboLocations.Items.Add(new Loc() { name = "Magikarp Nest - Amsterdam, Netherlands", lat = 52.373124, lng = 4.895865 });
comboLocations.Items.Add(new Loc() { name = "Dratini Nest - Sacramento USA", lat = 38.548232549872026, lng = -121.23232841491698  });
comboLocations.Items.Add(new Loc() { name = "Machop Nest - Tulsa,Zoo USA", lat = 36.210981, lng = -95.908203  });

**Comment by yupdon** [comment]
Adding this, verified with pokevision regarding nests locations worth adding??

https://www.reddit.com/r/pokemongola/comments/4t2jda/los_angeles_county_list_of_rare_pok%C3%A9mon_nests/

**Comment by chromeplatedhrt** [comment]
Nest Locations would be a great addition.
