### ISSUE TITLE
Location selection - see on pokevision

### ISSUE THREAD

**Issue by yupdon** [Novalys/PokemonGo-Bot-SimpleGUI#159]
Found it usefull, added this (locally) - should possibly become a thing?

![image](https://cloud.githubusercontent.com/assets/8333350/17238473/a1891ca0-5521-11e6-925f-d27f0962e83f.png)

![image](https://cloud.githubusercontent.com/assets/8333350/17238491/c6d839fa-5521-11e6-90ea-fad58fc36eef.png)

**Comment by PassiveModding** [comment]
this would be great, also possibly support for sniping pokemon

**Comment by Novalys** [comment]
Pokemon sniping is now live in version 1.5
