### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mich3lam** [Novalys/PokemonGo-Bot-SimpleGUI#16]
public ICollection<PokemonId> PokemonsToEvolve
        {
            get
            {
                //Type of pokemons to evolve
                _pokemonsToEvolve = _pokemonsToEvolve ?? LoadPokemonList("Configs\\ConfigPokemonsToEvolve.txt");
                return _pokemonsToEvolve;
            }
        }

        public ICollection<PokemonId> PokemonsNotToTransfer
        {
            get
            {
                //Type of pokemons not to transfer
                _pokemonsNotToTransfer = _pokemonsNotToTransfer ?? LoadPokemonList("Configs\\ConfigPokemonsToKeep.txt");
                return _pokemonsNotToTransfer;
            }
        }

How does this work? I've made a folder with the txt file inside, and let's say I put Magikarp in the don't transfer.. doesnt really work ? I guess?

**Comment by Novalys** [comment]
Ha... should explain before adding more stuff.. That's from the latest features that are being added to the main console application, I just added it for now to test, it's not yet implemented on the main GUI application :smile:

**Comment by mich3lam** [comment]
@Novalys Oh nice! Anyway to use it manually via GUI or that won't work until you implement whats needed? :D

**Comment by mich3lam** [comment]
@Novalys btw. why does after every first use the Coordinates inside the .txt file changes? They should not be tweaked with because it changes the location.. 

lets say i use -33.85901900:151.21309800 with 145 pokestops on the next time i open the bot, they'll be slightly different, close place but less pokestops, only 60

**Comment by Novalys** [comment]
It's a new feature added by the upstream team, it simulates walking towards the pokestops so it's not that obvious that we are teleporting on top of the location. Still with the new location selection in maps you should be able set the starting location more easily, I'm pushing the update in like 10min.

**Comment by Novalys** [comment]
Will close now as this should be fixed with tonight's build. Let me know if it doesn't.
