### ISSUE TITLE
[FIX] InvalidResponseException potential fix. Please test and tell me the results.

### ISSUE THREAD

**Issue by nxy** [Novalys/PokemonGo-Bot-SimpleGUI#164]
Edit "PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs" and replace with 

    public static class HttpClientExtensions
    {
        public static async Task<Response> PostProto<TRequest>(this HttpClient client, string url, TRequest request)
            where TRequest : IMessage<TRequest>
        {
            //Encode payload and put in envelop, then send
            var data = request.ToByteString();
            await Task.Delay(200);
            var result = await client.PostAsync(url, new ByteArrayContent(data.ToByteArray()));

            //Decode message
            var responseData = await result.Content.ReadAsByteArrayAsync();
            var codedStream = new CodedInputStream(responseData);
            var decodedResponse = new Response();
            decodedResponse.MergeFrom(codedStream);

            return decodedResponse;
        }

        public static async Task<TResponsePayload> PostProtoPayload<TRequest, TResponsePayload>(this HttpClient client,
            string url, TRequest request) where TRequest : IMessage<TRequest>
            where TResponsePayload : IMessage<TResponsePayload>, new()
        {
            Logger.Write($"Requesting {typeof(TResponsePayload).Name}", LogLevel.Debug);
            await Task.Delay(200);
            var response = await PostProto(client, url, request);

            if (response.Payload.Count == 0)
                throw new InvalidResponseException();

            //Decode payload
            //todo: multi-payload support
            var payload = response.Payload[0];
            var parsedPayload = new TResponsePayload();
            parsedPayload.MergeFrom(payload);

            return parsedPayload;
        }
    }

I believe the api is returning empty values if you send requests too quickly.. So I added some delay at the source.

EDIT: The delay varies. I believe it depends on the server you're connected to. So adjust as necessary. Sometimes there are spikes on the servers which causes InvalidResponseException errors.

**Comment by Venrir** [comment]
It works, thanks

**Comment by chromeplatedhrt** [comment]
I have edited it 3 different times and getting errors. Wants to run last stable build? But then stuck in the loops. Any idea of another fix? Or maybe I missed a step in the process?

**Comment by nxy** [comment]
Let me see your code for "PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs"

**Comment by yupdon** [comment]
This works for me as well! - Thought I'd put that out there. Can someone close #157 and other tickets referencing fixes?

**Comment by chromeplatedhrt** [comment]
Here is what I get when I click the link... 

![image](https://cloud.githubusercontent.com/assets/20599857/17255506/8f4272ce-5587-11e6-99c8-c7900b525227.png)

**Comment by chromeplatedhrt** [comment]
![image](https://cloud.githubusercontent.com/assets/20599857/17255675/3dab9f0c-5588-11e6-9a87-586c2a681a1a.png)

![image](https://cloud.githubusercontent.com/assets/20599857/17255684/45f2b682-5588-11e6-8708-dcfc7f54059a.png)

**Comment by nxy** [comment]
Add an extra } at the end of the file

**Comment by chromeplatedhrt** [comment]
That did it!! Thanks!!

**Comment by DosCrasher** [comment]
Is there a way you guys can upload the fix , just the modyfied files. Thanks
