### ISSUE TITLE
Pokemon Transfer Bug

### ISSUE THREAD

**Issue by arr0wed** [Novalys/PokemonGo-Bot-SimpleGUI#169]
If someone has already addressed this issue, my apologies. I didn't see it when I looked through the active "issues".

On 1.0 and 1.1 there is this bug where when I try to transfer Pokemon, I get:

<img width="330" alt="capture" src="https://cloud.githubusercontent.com/assets/20612119/17258528/54919912-5595-11e6-8bd0-d312df9f3f56.PNG">

Basically, after exactly three pokemon are transferred I get some "unhandled exception", that tells me to either continue or quit. Continuing simply stops the transfer, and if I start it up again it'll only transfer 3 more before the same error will pop up.

I am logging in via PTC if that makes any difference.

Here is the log, which doesn't have anything notable:
[log.txt](https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/files/391093/log.txt)

Let me know if there's any other information you need, and thanks for your help!

**Comment by nxy** [comment]
#164 Add some delay to your code.

**Comment by Firmalist** [comment]
Had the same problem, nxy's solution solved this problem.

**Comment by arr0wed** [comment]
Yeah, I'm sure that's the issue. I don't have VB on the computer I'm using, so I'll just wait until this has been fixed in the next update.

Also, the **total/maximum items in the bag** is still fixed at 350... which has been a noted problem for at least 5 releases now. Is it more complicated to fix than I thought?

**Comment by nxy** [comment]
There will be an update soon where the bag size will be fixed.

**Comment by A-Charvin** [comment]
The 350 Limit is imposed by the game. Unless you upgrade the bag the maximum capacity the bag can have is 350 Items. The number of items can vary as +-4 but the bag capacity as per the game default is 350.

**Comment by arr0wed** [comment]
You misunderstood my point, but it doesn't matter because @nxy already fixed it. See #178

**Comment by A-Charvin** [comment]
I just saw that issue thread you mentioned now. Good to know that the issue have been resolved. :+1:  :)
