### ISSUE TITLE
 I don't know what the problem is

### ISSUE THREAD

**Issue by LitoOsaka** [Novalys/PokemonGo-Bot-SimpleGUI#174]
Is my bot even running at all? I've tried both v1.1 and v1.2 and they both pretty much stuck on this screen . The green bar looks like its working but thats about it.
![capture](https://cloud.githubusercontent.com/assets/20585482/17268563/e3a110e0-562d-11e6-9204-0b3490ce7b65.JPG)

And this is all there is in the console

[08:17:13] Lucky Eggs in Bag: 0
[08:17:13] Pokemons in Bag: 1/250.
[08:17:13] Inventory and Pokemon Space, Ready.

**Comment by adamgyongyosi** [comment]
@LitoOsaka click PoGo Bot in menu and Farming And Start Bot

PoGo Bot > Farming > Start Bot

**Comment by LitoOsaka** [comment]
Oh wow, I feel like a derp now. Thank so much!
