### ISSUE TITLE
[GOOGLE LOGIN] How to login if on Google 2FA

### ISSUE THREAD

**Issue by adamgyongyosi** [Novalys/PokemonGo-Bot-SimpleGUI#175]
If you have on 2FA 

How to work boting:
- go website https://myaccount.google.com/security
- turn off and this program will work
- Login this program

but it is a big security problem i hope will @Novalys fix today

@Novalys https://twofactorauth.org/
#157 
#160

**Comment by Swearie** [comment]
I hope this will get fixed soon as well.

**Comment by Novalys** [comment]
That is correct, I didn't consider people with 2FA enabled, that why multiple people were not able to login, I'm coding the fix right now should be up in less than 1 hour.

**Comment by adamgyongyosi** [comment]
@Novalys thx

**Comment by Swearie** [comment]
Great!

**Comment by echo465** [comment]
Can you use an application password?

https://support.google.com/accounts/answer/185833?hl=en

**Comment by Novalys** [comment]
This has been fixed, well not fixed.. just added instructions on how to login using Google Account if you are using 2 Factor Authentication.

**Comment by adamgyongyosi** [comment]
@Novalys thx for fix
