### ISSUE TITLE
Bag Size

### ISSUE THREAD

**Issue by arr0wed** [Novalys/PokemonGo-Bot-SimpleGUI#177]
It seems I can start the bot with an over 350 inventory, but the console still displays out of 350.

<img width="238" alt="capture" src="https://cloud.githubusercontent.com/assets/20612119/17269767/a712570a-561f-11e6-9527-509381428874.PNG">

I'm logging in via PTC and my real bag maximum is 650.

**Comment by arr0wed** [comment]
Oh, and if possible, can you make it so the "My Pokemon List" feature (which is awesome, btw) is in a maximizable window? I have a lot of pokemon, so it'd be nice if I could make the window larger instead of scrolling so much.
Also, if there was a way to sort by name (and also possibly IV) instead of just CP, that would be awesome too.

**Comment by nxy** [comment]
#178 Storage display is fixed and is in the pull request

**Comment by arr0wed** [comment]
Thanks ^^
