### ISSUE TITLE
Pokemon evolution check

### ISSUE THREAD

**Issue by A-Charvin** [Novalys/PokemonGo-Bot-SimpleGUI#180]
An option to control evolution of Pokemon to reduce lose of candies.
Mode to evolve higher version of Pokemon.
#
Insted of wasting candies to evolve.
Poliwag -> Poliwhirl | Candies = 25
The evolution should focus on
Poliwhirl -> Poliwrath | Candies = 100

**Comment by Simpuhl** [comment]
Basically, when doing evolutions if there's an option for
complete_pokedex=true

then focus on completing the 3rd evolution before the second if you don't own the 3rd.

Also a list to specify which pokemon to only level the second version if it exists would be cool

**Comment by Dimexo** [comment]
Very good idea. The idea with completing the 3rd evolution  is in my opion a very good ideea

**Comment by UncleMart** [comment]
Yup, this would be a cool option :)

**Comment by Dyndrilliac** [comment]
Agreed. I left the bot unattended overnight and it evolved one of the many magikarp it had caught and blew 400 candies lol. No biggie but it would be helpful to have a safelist or something.

**Comment by Novalys** [comment]
This is a great idea, but it's really intensive as it would require to know which pokemon have 3th evolutions, will close this for now as I don't think I'll have the time to code something like this. But it's added to a list I have of ideas to improve the application.
