### ISSUE TITLE
Item Manager

### ISSUE THREAD

**Issue by Dimexo** [Novalys/PokemonGo-Bot-SimpleGUI#183]
A option to manage the number of every item would be nice!(If  the inv is full the bot´ll recycle all the items until you´ve got the number of items that you want to have. And if the bot´ve got that number of items collected and your inv is full  the bot´ll recycle the less rarely items until you´ve got just Masterballs :))

Like:
Pokeballs: <=number=>
Superballs: <=number=>
Hyperballs: <=number=>
Revive: <=number=>

and so on with every item you can get in pokestops. 

I´d like to have the transfer option not  togother with the evolve option so that i can decide myself what i´d like to evolve :)

Example bot by Ar1i: https://github.com/Ar1i/PokemonGo-Bot

Sorry for my bad english :)

**Comment by Novalys** [comment]
This has been acknowledged and has been added to my internal "features to add / bugs to fix" will close this for now since I want to keep issues only to open discussions about new features or actual issues. Thank you!
