### ISSUE TITLE
Auto recycle and release | Incubate and Hatch

### ISSUE THREAD

**Issue by A-Charvin** [Novalys/PokemonGo-Bot-SimpleGUI#184]
#Option to auto recycle items and release low cp Pokemon.
as well as options to incubate and hatch eggs.
and a counter to see the star dust count as well to complete the bot.

The implementations can be adopted from : https://github.com/PokemonGoF/PokemonGo-Bot

**Comment by Novalys** [comment]
Those features are being added in the upcoming version 2.0, thanks for the suggestion!
