### ISSUE TITLE
[Suggestion]An option for last been location

### ISSUE THREAD

**Issue by LitoOsaka** [Novalys/PokemonGo-Bot-SimpleGUI#189]
I was in Sydney poking around and I changed the timer between pokestops from 10 to 9 seconds and the program just stop doing anything, I waited a few min before I stop it and start again. I proceed to pick Sydney from the list, but now I flew too far from where I was and got a soft ban xD.

Its not really an urgent thing, I figured it would be useful if the program does crash.

**Comment by Novalys** [comment]
I think is not longer required as there is an option to quickly remove a soft ban in the latest version which you can download here https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/releases/latest
