### ISSUE TITLE
[Suggestion ]Evolve only Duplicate pokemons

### ISSUE THREAD

**Issue by dogras93** [Novalys/PokemonGo-Bot-SimpleGUI#190]
It would be very useful if there was an option to evolve only the duplicate pokemons you have.

**Comment by Markmanus** [comment]
Is is possible to separate in setting the Automatically evolve/transfer pokemons?

I personally prefer to evolve certain pokemons myself(especially magikarps..), but the automatic transfer itself amazing.

**Comment by A-Charvin** [comment]
There is a new pull request with a bunch of new options including the features you have mentioned. 
The author have acknowledged that the upcoming updated releases will implement the new features. :+1: :100:

**Comment by Novalys** [comment]
This has been added in the latest version https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/releases/latest Thanks!
