### ISSUE TITLE
All locations "You need to declare a valid starting location"

### ISSUE THREAD

**Issue by xxpowerxx1qz** [Novalys/PokemonGo-Bot-SimpleGUI#192]
Hi, a bit new to all this but whatever starting location I choose, it always ends up with "You need to declare a valid starting location" than the program closed to avoid a softban. What exactly is a valid starting location? None of the recommended farming sites work either.

**Comment by Novalys** [comment]
I have another user facing this exact problem. Wait until version 1.4 that is coming tonight, it will help me generate the error logs to see what is causing this problem.

**Comment by Novalys** [comment]
Download the latest version please https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/releases/latest and if you encounter this problem again there should be a Location.ErrorLog file in your folder, paste the contents here.

**Comment by orangecerberus** [comment]
Object reference not set to an instance of an object.

   at PokemonGo.RocketAPI.GUI.MainForm.DisplayPositionSelector()


That's what's in my location error log file.

**Comment by Dankinlake** [comment]
Hey got the same error log file with V1.4

**Comment by proxikal** [comment]
Same for me. Using 1.4 no matter where I put my location I get this issue. I've tried manually adding the coords in the inputs along with choosing on the map with the same output.

**Comment by hubbihen** [comment]
Object reference not set to an instance of an object.

   at PokemonGo.RocketAPI.GUI.MainForm.DisplayPositionSelector()

**Comment by TNTnight** [comment]
Object reference not set to an instance of an object.

   at PokemonGo.RocketAPI.GUI.MainForm.DisplayPositionSelector()

**Comment by Novalys** [comment]
Guys we are tracking this problem in #222 now, but basically download the latest version and try with that one and comment the output there. thanks
