### ISSUE TITLE
Unban not working

### ISSUE THREAD

**Issue by JordyGitHub** [Novalys/PokemonGo-Bot-SimpleGUI#193]
It appears that the (game) update of today has fixed the softban workaround...

**Comment by LitoOsaka** [comment]
Whats the softban workaround? Is it the login to a not ban account, catch a pokemon then log to a banned account to unban it?

**Comment by JordyGitHub** [comment]
No, the quick spin of pokestops

**Comment by Novalys** [comment]
Don't think so, I made an error while implementing this in version 1.3 which is fixed now in version 1.4 that should be up tonight. Just finished coding that and made some successful drastic location changes followed by a force unban.
