### ISSUE TITLE
recycleItemTimer causes a crash every so often

### ISSUE THREAD

**Issue by ryandailey100** [Novalys/PokemonGo-Bot-SimpleGUI#197]
![capture_error](https://cloud.githubusercontent.com/assets/15038444/17280452/469fab94-575e-11e6-9bbe-0dcdd6a36db8.PNG)

![capture2_error](https://cloud.githubusercontent.com/assets/15038444/17280463/9dcf9a1e-575e-11e6-867a-588640850497.PNG)

Every so often (around 30min - 1 hour) my program will crash due to this

**Comment by yupdon** [comment]
Confirmed. Also happening for me. Every once in a while my error read something like log is being used by another process. (Could be a separate issue however).

**Comment by Novalys** [comment]
This is a confirmed bug that is fixed in version 1.4 (which should be available tonight).
