### ISSUE TITLE
Location Group box - low priority feature improvement

### ISSUE THREAD

**Issue by yupdon** [Novalys/PokemonGo-Bot-SimpleGUI#199]
![image](https://cloud.githubusercontent.com/assets/8333350/17281089/cb23fa50-575e-11e6-887b-6b728db21aae.png)
Location - Name / or if one didn't use the ddl then Show coordinates?

When having multiple open it would be nice to see after a while as I forget where they were.

**Comment by LitoOsaka** [comment]
xD you can just zoom it out a bit and the map will tell you the name of the city/country/continent as you continue zooming out.

**Comment by Novalys** [comment]
I could actually add the coordinates in that section you suggest but I really think @LitoOsaka idea is way more helpful than 2 long numbers to tell you your current location, use the mouse scroll above the map to zoom in/out and you can easily see where you are located. Thanks!
