### ISSUE TITLE
Select Initial Location using Google Maps

### ISSUE THREAD

**Issue by Novalys** [Novalys/PokemonGo-Bot-SimpleGUI#2]
After the initial login I would like the user to be able to select the initial location using Google Maps.

**Comment by mich3lam** [comment]
@Whoa! Huge update there Novalys! Love your work! Are you implementing this too?

**Comment by Novalys** [comment]
Already have a working version but found a problem that is crashing the map, I won't go to sleep until this is online! lol

**Comment by Novalys** [comment]
Feature added on commit 6b1fdb4
