### ISSUE TITLE
Stopping 

### ISSUE THREAD

**Issue by mich3lam** [Novalys/PokemonGo-Bot-SimpleGUI#20]
http://i.imgur.com/YsjypeZ.png

why is it happening?

**Comment by Novalys** [comment]
You are using an old version, check out the latest release https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/releases/tag/v0.11-beta

**Comment by Novalys** [comment]
@mich3lam Can you confirm this solved your problem? or just close the ticket when you confirm this is fixed :+1:

**Comment by mich3lam** [comment]
@Novalys will do when i get home! :)

**Comment by mich3lam** [comment]
@Novalys yo, i was checking it and now when i clicked stop it started evolving my Pokemons? why?

**Comment by Novalys** [comment]
@mich3lam because it was a bug, this is fixed now in the latest commit 0dfdd18

**Comment by mich3lam** [comment]
@Novalys dude it's amazing how fast you spot things and get them fixed!
Is there anyway in code to tell it what NOT to trasnfer or do we need to wait for the .txt files update? :D

**Comment by Novalys** [comment]
@mich3lam yes, it's going to be included in the .txt files update, will close this for now as I already have an issue opened for that feature.
