### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by chromeplatedhrt** [Novalys/PokemonGo-Bot-SimpleGUI#200]
Is it possible to be able to choose what we recycle, instead of the major bag clean out? There are times it recycles hundreds of pokeballs. Was hoping to be able to pick and choose what to recycle and how much. Thanks for all the hard work! You've done an amazing job!

**Comment by Dyndrilliac** [comment]
I agree this would be a nice feature. Maybe a priority list? I know the two items I most want to hold on to are Ultra Balls and Razzberries, whereas I only need to keep a small number of revives and potions on hand. But my needs might be different from another user, so making it configurable is definitely the way to go. Also, add the recycle process to the automatic Transfer/Evolve step so I don't have to stop the bot. Also anything that adds user-interaction to the bot's farming behavior should be considered very cautiously, as most of us are probably running it unattended.

**Comment by Novalys** [comment]
This has been acknowledged and has been added to my internal "features to add / bugs to fix" will close this for now since I want to keep issues only to open discussions about new features or actual issues.
