### ISSUE TITLE
No items from Pokestops?

### ISSUE THREAD

**Issue by AiwisOne** [Novalys/PokemonGo-Bot-SimpleGUI#204]
since i use 1.4 i don't really get items from Pokestops. It look lite the bot use few spots.At earlier version my inventory are full between 1-2 round. Now my Items only rise around 10 items.

**Comment by A-Charvin** [comment]
Auto recycle option implemented to prevent bag from filling up.

**Comment by AiwisOne** [comment]
ok, thanks for information.
