### ISSUE TITLE
[feature request] define search radius for pokestops

### ISSUE THREAD

**Issue by cvbkf** [Novalys/PokemonGo-Bot-SimpleGUI#205]
hello,

is it possible to define the size of the search radius for the next pokestops. sometimes, there a lot of lures on pokestops, so i want to stay there and farm the pokemons and only the nearest pokestops. 

is that possible ?

**Comment by Novalys** [comment]
Not really, I don't think is worth the time to stay in a pokestop while you can walk to so many others, the exp gained by just getting to a pokestop beats the possible lures in one.
