### ISSUE TITLE
Text Change - speed defaults? [low priority]

### ISSUE THREAD

**Issue by yupdon** [Novalys/PokemonGo-Bot-SimpleGUI#207]
![image](https://cloud.githubusercontent.com/assets/8333350/17297806/d6c3dff6-57cc-11e6-923b-243d8d27c28c.png)

Can we change the text to "Speed (km/h)". Where driving average is like 50 km/h, and riding bikes around 15-25 km/h. Which I think we should default it to .. Riding bikes as, well, - it's faster than 5 :)

**Comment by Novalys** [comment]
Sure thing, will perform this in the next release.
