### ISSUE TITLE
Set Location [Release vs Debug low priority bug]

### ISSUE THREAD

**Issue by yupdon** [Novalys/PokemonGo-Bot-SimpleGUI#209]
In release when logged into my main account, I cannot select the times square (haven't tested others) location **(You must enter a valid location)**. I went to debug it - without flaw... Not sure how but thought I'd put this here in case others are having this issue.

**Comment by TNTnight** [comment]
I'm having the same issue too. I'm not sure why.

**Comment by hubbihen** [comment]
Object reference not set to an instance of an object.

   at PokemonGo.RocketAPI.GUI.MainForm.DisplayPositionSelector()

v1.4

**Comment by ScHaTTeNLiLiE** [comment]
Same problem here

**Comment by N02SRT** [comment]
Same here... :( Works for pre-Defined locations, just not custom ones. :(

Thanks for all that you do!

**Comment by Novalys** [comment]
OK I need a little bit of clarification here, does it works when you move the map and it generates the coordinates? or when you select from the list? or just doesn't work when you enter the coordinates manually?

**Comment by N02SRT** [comment]
Hey Novalys,

All of the predefined locations work fine, but if you move it in any sort of way... making it use "custom coordinates" it does not work. Will pop up wit the error "You must enter a valid location".

Here is the error:
![image](https://cloud.githubusercontent.com/assets/14588565/17313506/37401626-582a-11e6-86ad-5b9f3471f12b.png)

Thanks for the quick response!

**Comment by Novalys** [comment]
@N02SRT by move it you mean moving the map or typing the coordinates directly ?

**Comment by N02SRT** [comment]
@Novalys Both cause the same issue.

**Comment by yupdon** [comment]
This happens to me only in release. When starting out outside of visual studio. Selecting the new - new York - location [time square I believe, but haven't tested others]  or changing the lat long values or clicking on map near this location respectively.

**Comment by Novalys** [comment]
We are tracking this now in #222 please check that issue but basically download the latest version before and try with that one.
