### ISSUE TITLE
Set location pretends to work, but upon starting, returns to default location.

### ISSUE THREAD

**Issue by pavelmoulisjr** [Novalys/PokemonGo-Bot-SimpleGUI#21]
![picture 1](https://cloud.githubusercontent.com/assets/11504592/17077319/54f62f3a-50cc-11e6-83d6-bd679e79c5b1.png)
![picture 2](https://cloud.githubusercontent.com/assets/11504592/17077318/54f4b24a-50cc-11e6-8b51-5c9ded98fa01.png)

Reproduce: 
Set location anywhere (in this case random spot in Copenhagen)
Console says location is set correctly (see picture 1)
Start bot
Based on Pokestop name, bot starts in some sort of a default location, presumably London area (picture 2)

**Comment by Novalys** [comment]
Thanks for the report, the latest commit fixes this problem. If you are using Visual Studio to compile you should be able to download the source now and it will work, if you are using the compiled version release tomorrow morning I'll create a new release containing this change.

**Comment by pavelmoulisjr** [comment]
Confirmed, fixed!
