### ISSUE TITLE
Feature Move Request

### ISSUE THREAD

**Issue by yupdon** [Novalys/PokemonGo-Bot-SimpleGUI#210]
Can we add the other setting especially items recycle options to the settings here? I have X inventory space and i'm recycling as if i had 350 (default i believe).

![image](https://cloud.githubusercontent.com/assets/8333350/17299392/ca39639e-57d3-11e6-9cd6-4235cb2d0409.png)

**Comment by A-Charvin** [comment]
Good suggestion there. :+1:

**Comment by Novalys** [comment]
Yes of course we can, this is already in the works. Will close this for now since I only want to have open issues and discussions here.
