### ISSUE TITLE
v1.4 - Constantly recycles items down to 140-ish every few pokestops + suggestion

### ISSUE THREAD

**Issue by DecimationNation** [Novalys/PokemonGo-Bot-SimpleGUI#212]
With v1.4, my inventory constantly fluctuates between 130-170 items (out of 350) In v1.3 my inventory would always be full. Also, if it isn't too much trouble, an option to pick which items get recycled (and at timed intervals, or even the second you pick them up) would be amazing! At this point I'd love to only toss regular pokeballs, regular potions, and revives. Thanks for the AMAZING work so far! Love it!

Edit: even an option to set maximum number of each item, that'd be awesome too, because keeping a few revives around would be nice!

**Comment by A-Charvin** [comment]
The auto recycle option is there to ensure the bot works properly.
With a full bag the bot tends to close and crash in earlier builds if it was left as such for a while.
If you need more customization options please look into the code and change the values there.
The upcoming bot versions will incorporate more options as we speak.

**Comment by DecimationNation** [comment]
Thanks for the quick response! I'll have a look at the code

**Comment by Novalys** [comment]
A items list to recycle is in the works already. Will close this for now since I only want to have open issues and discussions here.
