### ISSUE TITLE
Pokemon Automatic Evolve [low priority request idea]

### ISSUE THREAD

**Issue by yupdon** [Novalys/PokemonGo-Bot-SimpleGUI#215]
I've worked on this myself and have it working, but I'm too new to Github to know what I'm doing as far as pushing my merge request. Any way, I've added a whitelist next to the setting for automatic evolve. 

I really wanted to choose myself which pokemon to evolve so i've put pidgy and ratatta in the whitelist as I don't care to evolve them manually, but I do want to choose to evolve a 80% 700cp pokemon over a 95% 10cp one.

**Comment by Novalys** [comment]
I already have plans to create a white list and black list for evolution, thanks for the suggestion! Will close this for now since I only want to have open issues and discussions here.
