### ISSUE TITLE
You need to declare a valid starting location

### ISSUE THREAD

**Issue by hubbihen** [Novalys/PokemonGo-Bot-SimpleGUI#216]
Cant use the bot because this pop up keeps happening? Anyone have any ideas on what to do??
![screenshot 331](https://cloud.githubusercontent.com/assets/20779491/17307231/d9d365e2-57e8-11e6-8932-892f9d8cffec.png)

**Comment by yupdon** [comment]
This is already an open ticket #209

**Comment by Novalys** [comment]
We are tracking this in #222
