### ISSUE TITLE
Possible Feature Improvement (Auto Transfer)

### ISSUE THREAD

**Issue by yupdon** [Novalys/PokemonGo-Bot-SimpleGUI#217]
I hate it when i get a bunch of CP 10's in my list the program wont' get rid of. I've added to my local solution a max CP to dispose of when transferring, in my case all duplicates < 400cp are trash to me, no matter the IV%.

**Comment by LitoOsaka** [comment]
Then put the value at 400cp and 100% IV, anything under 400cp at any IVs will get transfer. 401cp and above even at 1%IV stay. Easy peasy.

**Comment by Novalys** [comment]
What @LitoOsaka proposed is a good solution.
