### ISSUE TITLE
Feature improvement: when transferring duplicates, keep the pokemon with highest CP of that type

### ISSUE THREAD

**Issue by iKonatai** [Novalys/PokemonGo-Bot-SimpleGUI#218]
Lets say I have 3 ponyta's, one is 132CP, one is 68 cp, and the other is 347. When i transfer pokemon I notice that sometimes the bot will transfer the (as example used above) the 347 and the 68 leaving only the 132. What if you made it so it transfers all then lower ones so that way we can upgrade our pokemon and essentially make them OP

**Comment by Simpuhl** [comment]
Fuck CP, IV is more important

**Comment by Novalys** [comment]
That's how it works, it transfer the duplicates and leaves the highest CP / IV.
