### ISSUE TITLE
Wrong latitude/longitude

### ISSUE THREAD

**Issue by wygasmateusz** [Novalys/PokemonGo-Bot-SimpleGUI#22]
Always defauls starts in London ignore entered data latitude and longitude.

**Comment by Novalys** [comment]
This was fixed some minutes ago, pull the latest code or download the latest release:

https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/releases/tag/v0.11-beta

:smile:

**Comment by wygasmateusz** [comment]
Confirmed. Fixed in v0.11. Thanks

**Comment by Novalys** [comment]
@wygasmateusz Glad to hear, closing this now.
