### ISSUE TITLE
Unable to start the bot

### ISSUE THREAD

**Issue by mercurio2682** [Novalys/PokemonGo-Bot-SimpleGUI#220]
That is the only message i receive when i set the location, i installed this https://www.microsoft.com/es-ES/download/details.aspx?id=48145
Am i forgetting anything?

**Comment by iKonatai** [comment]
Same here man, its weird.

**Comment by sa1000408** [comment]
Same here.

**Comment by Novalys** [comment]
Guys we are tracking this problem in #222 please come and check if the solution proposed there works for you.
