### ISSUE TITLE
Unable to Set Location (Don't Duplicate, Comment Here)

### ISSUE THREAD

**Issue by AxelXlll** [Novalys/PokemonGo-Bot-SimpleGUI#222]
-_-

**Comment by Simpuhl** [comment]
So declare one?

**Comment by orakles** [comment]
Object reference not set to an instance of an object.

   at PokemonGo.RocketAPI.GUI.MainForm.DisplayPositionSelector()
thats what my error log shows - only happens when using google login though

**Comment by Simpuhl** [comment]
Can you share your config file?

also make sure your google user and password are in between quotes like "blah@google.com" and "password"

**Comment by Novalys** [comment]
@AxelXlll try with version 1.5 and let me know if that works for you, in case it doesn't check inside the Log folder and send me the files that are there please.

**Comment by AxelXlll** [comment]
It works !!!!! Thank you so much!
