### ISSUE TITLE
Unable to start bot.

### ISSUE THREAD

**Issue by iKonatai** [Novalys/PokemonGo-Bot-SimpleGUI#224]
Title says, I am using the same username and password as usual but it wont let me log in with my account, and when i use my alternate account it seems to login and start the bot just fine.

**Comment by Novalys** [comment]
Could you provide more information like if you are using Google or PTC and what is the error message you are getting?

**Comment by Nexoru** [comment]
@iKonatai (ONLY IF PTC!!)  I just got the Problem 2 Days ago ... Log in to your PTC account at the Pokemon Homepage and Activate it. For some Reason 2 of my Accounts got De-Activated so resend me the email and activate it again , maybe it helps

**Comment by dasinking** [comment]
Had the same problem (with a Google account) at exactly Level 15 with 100000XP. "Fixed" it by getting a little more XP by myself, strangely enough.

**Comment by iKonatai** [comment]
@Novalys 
I am able to log in using my PTC account, but not my google account with the bot. I have tried logging in from different computers and IP addresses, and the error message just says "Unable to Start bot"

**Comment by Novalys** [comment]
Are you using the latest version of the bot? Also could you share the log
files inside you logs directory? Please delete all of them then try to
login again and when you get the error then share the files.

**Comment by iKonatai** [comment]
@Novalys I just tried to sign into the account VIA google with the newest bot, and it's suddenly working. Next time I experience issues I will attatch the logs.
