### ISSUE TITLE
1.5 dont start farming

### ISSUE THREAD

**Issue by Nexoru** [Novalys/PokemonGo-Bot-SimpleGUI#226]
I just downloadet Ver1.5 and when i click START, the bot says that he can start but he will not jump to the next stop or even find Pokemons ... tested on 6 accounts

and when i try the new snipe feature , this error comes : 

System.ArgumentOutOfRangeException: Argument must be in range of -90 to 90
Parametername: Latitude
   bei GeoCoordinatePortable.GeoCoordinate.set_Latitude(Double value) in C:\projects\geocoordinate\src\GeoCoordinatePortable\GeoCoordinate.cs:Zeile 109.
   bei PokemonGo.RocketAPI.GUI.PokemonSnipingForm.<btnSnipe_Click>d__6.MoveNext()

**Comment by Novalys** [comment]
You should have some log files inside a log folder, could you delete all of those then try again to farm or snipe and if you get the error, paste the contents of the files here?

**Comment by Lain818** [comment]
hello, i think the bot is jumping places a bit weird - like pokestops 36-100; then it shows for a second 43-100 then goes 37-100 and so on.

Enclosed the error files
[CatchingNearbyPokemonError.20160802094301.txt](https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/files/395491/CatchingNearbyPokemonError.20160802094301.txt)
[CatchingNearbyPokemonError.20160802093709.txt](https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/files/395492/CatchingNearbyPokemonError.20160802093709.txt)
[CatchingNearbyPokemonError.20160802094231.txt](https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/files/395493/CatchingNearbyPokemonError.20160802094231.txt)

**Comment by byzette** [comment]
Hi,

I got the same issue when i try to snipe ^^.
Btw farm is working for me :)

------------
System.ArgumentOutOfRangeException: Argument must be in range of -180 to 180
Parametername: Latitude
bei GeoCoordinatePortable.GeoCoordinate.set_Latitude(Double value) in C:\projects\geocoordinate\src\GeoCoordinatePortable\GeoCoordinate.cs:Zeile 109.
bei PokemonGo.RocketAPI.GUI.PokemonSnipingForm.d__6.MoveNext()

--------

I've tried many way to write the location but he doesn't let me try :(

**Comment by Nexoru** [comment]
@Novalys I deleted everything in the logs folder but when i snipe it will not create a new file. 
Result of the Snipe Box : 
System.ArgumentOutOfRangeException: Argument must be in range of -90 to 90
Parametername: Latitude
   bei GeoCoordinatePortable.GeoCoordinate.set_Latitude(Double value) in C:\projects\geocoordinate\src\GeoCoordinatePortable\GeoCoordinate.cs:Zeile 109.
   bei PokemonGo.RocketAPI.GUI.PokemonSnipingForm.<btnSnipe_Click>d__6.MoveNext()

**Comment by Novalys** [comment]
Sniping is in Beta right now, I'm aware of some of the bugs it has and currently working in fixing those. Thanks for the reports!
