### ISSUE TITLE
Can u please add an option for items

### ISSUE THREAD

**Issue by WolfyxBerg** [Novalys/PokemonGo-Bot-SimpleGUI#227]
Please add an option to keep items it keeps wasting my ultra balls to catch pokemons i would like to use only pokeballs or greatballs for example other than that the bot it's amazing by far the best from others!!
Thanks in advance!

**Comment by Novalys** [comment]
Thanks for the comment and yes, this is planned in the next release!

**Comment by WolfyxBerg** [comment]
Thank u very much!!!!
