### ISSUE TITLE
[Question] Will login override bot location?

### ISSUE THREAD

**Issue by OTTORE** [Novalys/PokemonGo-Bot-SimpleGUI#229]
With the bot running a few miles away will it override the location when I sign in on my phone? if so would it help to simply turn off GPS? This would be for things like incubating an egg with the bot walking around and what not

**Comment by JordyGitHub** [comment]
It will help if you turn off GPS when using your phone. I've been doing the same. One problem however, I'm unable to sign out that account on my phone because of this huge red bar saying that there is no location! As workaround (on Android) i just clear the cache and login in my real account again.

**Comment by Novalys** [comment]
It won't override it. If you use the software in USA (example) and you open your phone located in Europe it will "Teleport" you to that location and when you come back to the application it will return "teleporting" to USA which most likely cause a soft ban, which you can remove with the "remove soft ban" feature so no worries!

**Comment by OTTORE** [comment]
excellent, thank you both for the response! I appreciate the work thats going into this!
