### ISSUE TITLE
Farm Pokéstop

### ISSUE THREAD

**Issue by Superniz** [Novalys/PokemonGo-Bot-SimpleGUI#231]
Hi guys, thanks for your great job !

Im just wondering if you're considering an option for farm Pokéstop only ? It could be awesome to take some pokeballs without farming Pokémon :)

Again, thanks for that ! I have no knowledge of programming, but if you need help to translate in french, im here ;)

**Comment by Novalys** [comment]
I didn't think someone would be interested in this, but sure I'll add this as an option in the settings for the next release. Thanks!

**Comment by Superniz** [comment]
Thank you for your responsiveness ! It will be very useful for those who have no more Pokeballs.

You're my hero :D
