### ISSUE TITLE
Farming Issue 

### ISSUE THREAD

**Issue by Allusive** [Novalys/PokemonGo-Bot-SimpleGUI#233]
With the latest update the sniping tool is really helpfull but casual farming is now messed up . I sniped for some pokemon returned to my normal position but i keep getting banned or moving upside down on the map without catching anything . I forced remove ban it says that the ban got removed successfully but after some pokestops its still there ,plus its annoying that i have to wait certain seconds before i get to the pokestop to walk towards it !

**Comment by cucurettu** [comment]
Have you tried to remove the soft ban with the manula method? Open, roll, close, open roll, close quickly  ... one pokestop?

**Comment by Novalys** [comment]
@Allusive if you don't like/want the Human Walking method you can always disable it in the Settings options. Regarding the sniping -> farming that is correct there is a current bug in that which after sniping you don't come back to the original position. Closing the app after sniping fixes this for now but I'm already working in a permanent fix. Thanks!
