### ISSUE TITLE
Enhancements - Show Location

### ISSUE THREAD

**Issue by mich3lam** [Novalys/PokemonGo-Bot-SimpleGUI#25]
Right after it shows the player info (before you click start farming) maybe it should show where we chose to farm.. something like:
Logger.Write("You have chosen to bot at: ")

**Comment by wygasmateusz** [comment]
Yes it will be very helpfull , now i got softban becouse my bot jumped to location Gambia 2010 . It will be more safe if we will known where bot will start.
