### ISSUE TITLE
all pokemons got away

### ISSUE THREAD

**Issue by ramil111** [Novalys/PokemonGo-Bot-SimpleGUI#26]
i teleport to london and all pokemons the bot fight to have escaped, bug?

**Comment by EnigmaIsWorking** [comment]
that what you call softban for ~1  hour

**Comment by ramil111** [comment]
this is soft ban? i dont have any information about that, i can esily log in with out any problems

**Comment by asyven** [comment]
next time wait a ~1-2hour before tp a long distance

**Comment by ramil111** [comment]
okay, but now i tp to the close place and have same history

**Comment by ramil111** [comment]
where can i get to know that i am banned

**Comment by asyven** [comment]
nowhere, all pokemons got away and 0xp frop poketstops

**Comment by EnigmaIsWorking** [comment]
Edit in App.config before starting the last GPS postion you had less than an hour. Do not teleport to fast. I would also prefere 10 km/h than 50 in config.

When you are softbanned you don't get any Experience and all Pokémon run away... Use Google for more information.

<setting name="WalkingSpeedInKilometerPerHour" serializeAs="String">
        <value>EDIT HERE</value>

   <setting name="DefaultLatitude" serializeAs="String">
        <value>EDIT HERE</value>
      </setting>
      <setting name="DefaultLongitude" serializeAs="String">
        <value>EDDIT HERE</value>

**Comment by ramil111** [comment]
well... will be i unbanned?

**Comment by ramil111** [comment]
and where can i find configs?

**Comment by EnigmaIsWorking** [comment]
This is no chat. Read the project or simple use search.... `STRG+F`
Everytime you teleport from 1 position to another (to long distance, to fast), you get softbanned for **~1 hour**.

**Comment by ramil111** [comment]
i have already unbunned, i want to change km/h in appconfig, but i really can't find it, i have download pogo-simple gui 0.11 beta, there is no PokemonGo.RocketAPI.GUI/App.config, sorry for bad english

**Comment by Novalys** [comment]
Yes this is a soft ban, could any one help me creating some notes or instructions about the soft ban to add them to the README ?

**Comment by EnigmaIsWorking** [comment]
I can write some notes for preventation, but most users here don't care and just want to bot.
The best solution would be, that after Login, the bot doesn't send default GPS to the server and after that asks where to start... You can connect to the account even without giving GPS. (Evolving, and Items clean up possible). Clicking on start farming should set the GPS and start the real logic.
