### ISSUE TITLE
Bot is not working anymore.

### ISSUE THREAD

**Issue by Makozer** [Novalys/PokemonGo-Bot-SimpleGUI#269]
1.4 and 1.5 Version wont work anymore since auth problems ... auth is possible again but nothing happens anymore.

**Comment by henne3737** [comment]
Ive got exactly the same problem. had authentication problems like 10 minutes ago. login works again, but then... nothing happens. cant farm, cant remove ban, cant snipe, just nothing happens at all. not even an error code. tried 1.4 and 1.5

**Comment by NoFootprintsGG** [comment]
+1 farm process doesn't get initiated

**Comment by Alessandro321** [comment]
same here :/

**Comment by xXDarkBladeXx** [comment]
same here

**Comment by qwertychacha2002** [comment]
same here :/
