### ISSUE TITLE
NVM

### ISSUE THREAD

**Issue by LiquidPossum** [Novalys/PokemonGo-Bot-SimpleGUI#272]
No issues

**Comment by BootNati0n** [comment]
Please read issue #271..

**Comment by Samsonight** [comment]
Perhaps read [READ BEFORE POSTING] Bot not working....

**Comment by kelbouz** [comment]
Niantic has changed API it doesn't work anymore, they know it and if you would have read, the thread just before the one you write.....is explaining it...

**Comment by Sbrown-WilliamsCrusher** [comment]
Please comment and close :)
