### ISSUE TITLE
What's this???

### ISSUE THREAD

**Issue by cyberpunk2k7** [Novalys/PokemonGo-Bot-SimpleGUI#273]
![1](https://cloud.githubusercontent.com/assets/20825993/17384035/80207b78-59d9-11e6-8751-fe8dbf37c401.PNG)
Care to explain this please? Thank you.

**Comment by devilesh** [comment]
its working just fine no viruses i tried it but there is a new api so the bot will not work for now

lets hope they fix it by today or tomorrow as niantic released a fix patch so the api was changed 

we need to update the bot so there is nothing to worry about cause the devs are active and doing their best ...

**Comment by cyberpunk2k7** [comment]
@devilesh Why did my scan show this then? i got 2 hits on this. Im just asking. Thanks!

**Comment by minifreddusch** [comment]
You can just download the source code, check it, and compile yourself if you wish to. It doesn't contain any malware, and I don't know why your antivirus is showing this up :)
However for now the bot won't work as @devilesh said.

**Comment by cyberpunk2k7** [comment]
@minifreddusch I did that and it doesn't but i just can't get what triggered that. This is the 1st time i ever got this :))

**Comment by Sbrown-WilliamsCrusher** [comment]
Sometimes open source projects like this trigger a false positive. but always good to check code to see if someone is trying to harm your machine. Ive looked nothing malicious but you can look aswell

**Comment by Novalys** [comment]
This is a false positive but if you feel insecure you can always download the source and compile it yourself. Thanks!
