### ISSUE TITLE
Bot crashs and fails to restart.

### ISSUE THREAD

**Issue by shadowsyllvet** [Novalys/PokemonGo-Bot-SimpleGUI#28]
The bot crashed and failed to restart then proceeded to fill the installation folder with a new crash log file every 5 seconds.
Edit: deleting the middle 200 crash logs as there's no way to put them in a collapsible spoiler tag using markdown

[CrashLog.201607230705394617.txt](https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/files/379544/CrashLog.201607230705394617.txt)
[CrashLog.201607230705448171.txt](https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/files/379541/CrashLog.201607230705448171.txt)
[CrashLog.201607230705499579.txt](https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/files/379543/CrashLog.201607230705499579.txt)
...   ...   ...   ...
[CrashLog.201607230705241172.txt](https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/files/379747/CrashLog.201607230705241172.txt)
[CrashLog.201607230705292268.txt](https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/files/379749/CrashLog.201607230705292268.txt)
[CrashLog.201607230705343521.txt](https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/files/379751/CrashLog.201607230705343521.txt)

[/spoiler]

**Comment by A-VORONKIN** [comment]
Same problem

**Comment by yingsta** [comment]
On latest version and I get the same thing, 

[CrashLog.201607230818199330.txt](https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/files/379774/CrashLog.201607230818199330.txt)

**Comment by Novalys** [comment]
This is already reported and is being tracked on issue #42 will close this one to avoid duplicates, thanks for the report!
