### ISSUE TITLE
PokemonGo.RocketAPI.Exceptions.InvalidResponseException

### ISSUE THREAD

**Issue by hy418618674** [Novalys/PokemonGo-Bot-SimpleGUI#29]
running 1h later, throw a PokemonGo.RocketAPI.Exceptions.InvalidResponseException

if (response.Payload.Count == 0)
                throw new InvalidResponseException();   //thrown at this line. in funtion PostProtoPayload()

**Comment by Novalys** [comment]
This is already reported and is tracked on issue #42 will close this one to avoid duplicates, thanks for the report!
