### ISSUE TITLE
Amazing bot - but I found a couple things...

### ISSUE THREAD

**Issue by arr0wed** [Novalys/PokemonGo-Bot-SimpleGUI#30]
This is such an awesome bot you made, I feel a little unsure about bringing up any issues lol... but I'm coming from a place of constructive appreciation :D.

- The inventory appears to have a set maximum value of 350, even though the inventory is expandable. For instance, my inventory can hold 650 items, so I had to delete a lot of great balls to even use the GUI.
- The window frame has a set size, by which I mean it can't be resized.
- There doesn't seem to be a way to stop certain actions, such as evolving all "evolvable" Pokemon, without closing the program. I could see the button(s) changing to "Stop Action", and functioning as such, after they are clicked and/or activated. I noticed you're already addressing a similar problem, which is that the evolve/transfer action happens automatically when you stop farming.

Far and away, this is the best bot I've found so far. Thank you for putting it together!

I'm viewing this as a beta of sorts, so unless you tell me to shove off I'll post more if I find anything ^^.

Thanks again.

**Comment by UncleMart** [comment]
The evolving thing is a known bug, has been fixed in the code and the next exe will have the fix :)

**Comment by TehEbil** [comment]
In addition, you should add the possibility to use a lucky egg before evolving all pokemon and "transfer duplicate Pokemon" should only delete unneccesary Pokemon, like:
you got 150 pidgy bobons and 30 pidgies. So it should delete (150 / 12) = 12,5 evolvable pidgies, 18 pidgies can be deleted. -> +18 candies, so only 16 can be deleted (need to calculate a  nice formula).

Btw.: I read, that some guys change their places, like training in New York, Japan etc. Why won't they get banned?

**Comment by arr0wed** [comment]
TehEbil, my understanding is that the use of lucky eggs or incense while using a bot results in instant soft bans. As such, the issue with having some type of lucky egg option is overcoming the increased likelihood of getting banned. Otherwise, I agree that such a feature would be cool. 

...I feel like we're getting a bit off topic from my original post lol...

**Comment by Novalys** [comment]
You have arrived to a place where any kind of feedback and suggestions are welcomed. There is already a plan to make the layout of the application responsive to the window size (currently locked). The inventory size is indeed a known bug and it's going to be addressed in the next release and regarding the options to stop certain actions, there is also a plan to create a settings view where you can tweak some of the bot options. 

Thanks a lot for the well redacted feedback, really appreciate it.
