### ISSUE TITLE
Location setting doesn't work

### ISSUE THREAD

**Issue by Agandir** [Novalys/PokemonGo-Bot-SimpleGUI#31]
Whatever i set, both in the gui or the coords file, it start on the default location in the usa, causing the soft-ban

**Comment by wygasmateusz** [comment]
You need you pick one of location and after choose your location by map  and i must me close to poketstop if not it will back to default location USA etc.

**Comment by TehEbil** [comment]
And use dots instead of commas

**Comment by Novalys** [comment]
Could you share a screenshot of you using the map to the location you require?

**Comment by wygasmateusz** [comment]
First time i need to choose diffrent location and after drag map to my location.
Good side is that in next application ussage location is remmembered so it is not so inconvinient.

If i need to change location i log on my testing account to check if bot start in good location and after log on main account.
![1](https://cloud.githubusercontent.com/assets/14853729/17079647/0f0789b0-5117-11e6-9039-997a7801d1d5.jpg)
