### ISSUE TITLE
Stopping Farm Issues

### ISSUE THREAD

**Issue by jinhaoxuan** [Novalys/PokemonGo-Bot-SimpleGUI#32]
How do you use the fix Novalys create for the new version?

Fixed a problem where stoppping the farming will trigger evolve/trans

PokemonGo.RocketAPI.GUI/MainForm.cs

where should i put the code shown? i dont see the .cs file in my bot folder
Thanks and sorry im newbie

**Comment by UncleMart** [comment]
Unless you know how to compile the project I would either just hold tight till a new exe releases or just force quit the bot when you want to finish using it.

To compile the project you'd probably need to download visual studio and do a bunch of messing around setting up, so it honestly might be easier for you to hold out for a new version for the time ;)

**Comment by jinhaoxuan** [comment]
figured that out :)
i downloaded the code instead and fix it will try after my softban is over
i'm closing this issue
Thanks for the reply
