### ISSUE TITLE
Farming Issue's Pokemons Will Run

### ISSUE THREAD

**Issue by Tombraider** [Novalys/PokemonGo-Bot-SimpleGUI#33]
Yesterday the bot was fine in a certain location but when i change the location pokemon will constantly run away even a 10 cp runs lol, i just thought you needed to know, i'm looking for this bug but i cannot find it yet.

**Comment by UncleMart** [comment]
It's a soft ban. The same will happen if you use fake GPS to move too far, too quickly. Soft bans will last somewhere between 20-60 mins and then you'll be able to capture pokemon and use poke stops again. I would suggest not moving too far between sessions ;) But yeah, this isn't exactly a problem with the bot but just some protection the game has to stop cheating GPS hacks ;)

**Comment by Tombraider** [comment]
Oh lol, i havent thought of that xD thank you

**Comment by Novalys** [comment]
Yes, soft ban. Give it at least 12 hours before trying again. Closing this for now :smile:
