### ISSUE TITLE
Enhancement: Menu For Evolving and Transfer

### ISSUE THREAD

**Issue by Khayalan** [Novalys/PokemonGo-Bot-SimpleGUI#35]
It would be really cool if we could have a menu (a list or something) of all our pokemon and then choose which we want to dismiss and which we want to evolve, hopefully with display of IV :)

**Comment by Novalys** [comment]
Oh, this would indeed be a nice feature, added to the list! Thanks.

**Comment by Novalys** [comment]
This has been added.
