### ISSUE TITLE
Save highest CP Pokemon when transffering

### ISSUE THREAD

**Issue by Foulwerp** [Novalys/PokemonGo-Bot-SimpleGUI#37]
When transferring duplicates it seems to transfer the highest CP Pokémon first, it should skip the highest CP one and transfer the rest.

**Comment by UncleMart** [comment]
I think this is because the bot will transfer based on the invisible IV stats rather than CP. A high CP value is less important than the IV stats. I'm not 100% sure of this though so maybe the dev or someone who has scanned the code can say :)

**Comment by Novalys** [comment]
@Foulwerp that's the way it's supposed to be working, I haven't really take a deep look as I don't really care for pokemon right now only experience, but definitely will check and fix if that's the case!

**Comment by adrscott** [comment]
I second this. Would be cool to have a feature that can loop through an array of duplicates and keep the highest cp when calling the transfer function.  if (i < max) { transfer }

**Comment by alecstheone** [comment]
Looking forward for this feature too. Thanks!!

**Comment by Novalys** [comment]
This has been added.
