### ISSUE TITLE
change speed between moving

### ISSUE THREAD

**Issue by tatgod91** [Novalys/PokemonGo-Bot-SimpleGUI#39]
the bot says waiting 10 secs how ccan i change it to like 2-5 secs

**Comment by UncleMart** [comment]
There's no way to do this with config files at the moment, you'll have to request it as a feature or change the code and compile it yourself :)

**Comment by Wyn10** [comment]
[MainForm.cs#L725](https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/blob/master/PokemonGo.RocketAPI.GUI/MainForm.cs#L725) & [MainForm.cs#L795](PokemonGo.RocketAPI.GUI/MainForm.cs#L795)

**Comment by Novalys** [comment]
It was indeed in the plans to add a config panel where everyone can tweak the timers to their liking (even when lower timers are more easy to detect, but that would be up to the user choice).

**Comment by Novalys** [comment]
This has been added.
