### ISSUE TITLE
Incorrectly logging into gmail?

### ISSUE THREAD

**Issue by Jordan155** [Novalys/PokemonGo-Bot-SimpleGUI#40]
So I just downloaded the bot and tried to use the google login with my account.

It sent me to the new tab window to enter the code for access to the new device.

It then said I was logged in but a level 1 and not the actual account associated with the gmail account I had entered into the "username" field.

Not sure exactly what is happening here.

**Comment by UncleMart** [comment]
While I'm not 100% sure on this, I think it's because the tutorial hasn't been completed yet. If I remember correctly, an account has been botted with but never logged in to and had the tutorial finished will register as level 1. Once you finish the tutorial you'll get a bunch of levels all at once and it should look ok again :)

**Comment by Jordan155** [comment]
It looks like it is actually just logging into the first account I logged in with and not overriding it with the new account.

**Comment by UncleMart** [comment]
Try what I suggest in this post : https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/issues/41

**Comment by Jordan155** [comment]
Sadly I don't really see a location to edit the account. It simply says "gmail" and not my account like it is showing for a PTC login.

**Comment by Novalys** [comment]
Just to confirm, if you want to login with Google you don't need to enter anything in the username and password field, that's only for PTC. But currently there is no option to switch from Google accounts once you create a token for the first one, I'm going to create this button so this is possible.

**Comment by Novalys** [comment]
This is being tracked in the Issue #41
