### ISSUE TITLE
Storing wrong Google Account

### ISSUE THREAD

**Issue by chromeplatedhrt** [Novalys/PokemonGo-Bot-SimpleGUI#41]
I tried out the bot with a google account I really don't use just to see how it worked. I want to use my actual Google account, but even when I enter the correct Google account info it still brings up the player info from the test account. Even with different login credentials? Any suggestions??

**Comment by UncleMart** [comment]
Try logging into the account on the device and finishing the tutorial if you haven't done so already. Once you've done that, log back in on the bot and it should display correctly. If this doesn't solve it then I'm unsure but will check back in case I can think of anything else :)

**Comment by chromeplatedhrt** [comment]
The tutorial on the test account was completed. Now the problem is that when I put in my actual account it still brings up the test account even though it is different credentials.

**Comment by UncleMart** [comment]
I see, that could indeed be a bug. For now you might be able to manually insert the correct information in the PoGoBot-GUI.exe.config file, if the google info isn't in there it'll be in : 

C:\Users\YOURUSERNAME\AppData\Local\PokemonGo\PoGoBot-GUI.exe_Url_BIGLONGRANDOMSTRING\1.0.0.0\user.config

**Comment by chromeplatedhrt** [comment]
Thanks I will try that and let you know.

**Comment by pavelmoulisjr** [comment]
Temporarily, where is the token stored? I can't even seem to find it right now, it's bugging the hell out of me.

**Comment by AliAlhabib** [comment]
download the zip file again and link the new code with a different google account

**Comment by chromeplatedhrt** [comment]
A reset token would be awesome! Thanks man!

**Comment by Novalys** [comment]
This has been added.
