### ISSUE TITLE
Stop auto evolving

### ISSUE THREAD

**Issue by adrscott** [Novalys/PokemonGo-Bot-SimpleGUI#43]
The bot automatically evolves everything that is duplicated (and completely ignores the "keep min CP" settings). How to prevent this?

Edited --

**Comment by mich3lam** [comment]
this was fixed here https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/commit/0dfdd18e6c059d9a0cb17e2fe86c5077a8142073

download the new version

**Comment by Novalys** [comment]
@adrscott The keep min CP feature hasn't been enabled on the Bot yet. Will mark this as a feature request and will implement it soon. Thanks for the report!

**Comment by Novalys** [comment]
This has been added.
