### ISSUE TITLE
Choosing pokemon not to evolve

### ISSUE THREAD

**Issue by tyfn61** [Novalys/PokemonGo-Bot-SimpleGUI#44]
Hey great job and i wanna thank you for this work :) 
I have some humble requests and it would be great to see them in the next versions.
Can we choose to pokemons to evolve and transfer or if this is not possible at least can we choose our pokemons which we dont want them to evolved or transsferred.  And it would be great that if auto evolve does not evolve weedle caterpie and pidgey to 3rd form cuz its was of candy and experince.
Thanks in advance :)

**Comment by Novalys** [comment]
This has been added.
