### ISSUE TITLE
How to add a new location? for example italy

### ISSUE THREAD

**Issue by IldeNet** [Novalys/PokemonGo-Bot-SimpleGUI#46]

**Comment by Mineroboter** [comment]
What do you mean with add new location? The locations in the checkbox are some suggestions. Just use the map to set the location (red crosshair) or paste Latitude and Longitude in the boxes.

**Comment by darkhax** [comment]
The UI does not have a user entry list yet, however you can add locations manually by adding a new line of code. Alternatively you can make a request on this [issues](https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/issues/17).

If you navigate to `PokemonGo.RocketAPI.GUI/LocationSelector.cs` you will see some code that looks like `private void addGoodFarmingLocations()` and inside the curved braces there will be several lines that look like `comboLocations.Items.Add...` you can add new locations here by copying a line, changing some of the info and adding it. Example code line below, just replace the all caps parts.

`comboLocations.Items.Add(new Loc() { name = "LOCATION_NAME", lat = LATITUDE_HERE, lng = LONGITUDE_HERE });`

**Comment by IldeNet** [comment]
Thanks for the prompt response. I mean, if I want to change the longitude and latitude in the map window. does not save the location from the text boxes and located in the United States.
I apologize for my English.

**Comment by Wyn10** [comment]
[PokemonGo.RocketAPI.GUI/LocationSelector.cs#L39](https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/blob/master/PokemonGo.RocketAPI.GUI/LocationSelector.cs#L39)

**Comment by Novalys** [comment]
@IldeNet for now the only option to add locations is to make a [request here](https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/issues/17). But if you think it would be useful you can also raise a ticket so we allow to add custom locations from the GUI.
