### ISSUE TITLE
Possible Perma-ban?

### ISSUE THREAD

**Issue by arr0wed** [Novalys/PokemonGo-Bot-SimpleGUI#48]
Perhaps someone with a solid understanding of Pokemon GO bans can give me some advice..

I understand that soft bans should last anywhere from 5 minutes to 2 hours. My issue is that around 5 hours ago I attempted to move to a new location, "maybe" 2 miles from where I was before. I waited about 10 minutes before doing this. At this new location I was getting the typical 0XP and no catches that come with a soft ban. I waited 45 minutes and tried again, but I was still getting no XP and no catches. I waited an hour and tried to go back to my previous location, but still saw the same soft-ban response.

I tried a different GUI to see if something had happened with this one, but no improvement.

I waited a full 2 hours, and tried connecting to that same location on this GUI (no change in the coordinates), and still nothing.

I have no problem logging in to the account on my phone, with the GPS disabled. Because my usual farming location is somewhat far from my house, I never enable GPS when I check my account on my phone. Thus, I can't say whether the account will work on my phone if I activated GPS.

If you have experienced something like this _and/or_ know of a solution, please help a sister out.

**Comment by UncleMart** [comment]
It could be that soft bans "accumulate" and can be added to each other. I've never had more than 20 minutes but I would think that someone who might trigger it say 3 times in a row in a few minutes might get an hour long one. It's the only thing I can think of :(

**Comment by arr0wed** [comment]
Well that's the thing: I never "moved" locations without waiting at least 45 minutes (after the first time.) And even then I waited 10 minutes before moving 1 or at most 2 miles. By now, I haven't used any bot in almost 2 hours, and I'm afraid to do so. I need some advice as to what I should do before trying the bot again, or how long I need to realistically wait (advice like "wait 24 hours" sounds like an exaggerated amount of time for just a soft ban). And if this really is more than just a soft ban, what did I do that other ppl aren't doing?

**Comment by Novalys** [comment]
In my personal experience I have been soft banned for up to 20 hours in one of the accounts, I don't know if there is something like a "accumulated" ban from multiple soft bans. For now the best is to just use alt accounts and keep your main account legit.

**Comment by shadowsyllvet** [comment]
Soft bans are distance specific. If you travel more than 500 meters in a few seconds you get a one minute ban. If you travel 2 miles in a second you get a 5-10 minute ban. If you travel 60 miles it's about a 45-60 minute ban. Traveling across the country will generally get you a ban for 12hrs+(depending on the size of the country ofc). Were you using a "pokeradar" style app with the account you were bottling?
