### ISSUE TITLE
[dev] can't compile sources 

### ISSUE THREAD

**Issue by asyven** [Novalys/PokemonGo-Bot-SimpleGUI#49]
So much errors, visual 2013

http://imgur.com/a/ikVXf

15 Required, "static" is the key word 
16 is required class, delegate, enum, interface, or structure of the..

**Comment by Wyn10** [comment]
![c9b7b992c5065643fa76dacb47c715a3](https://cloud.githubusercontent.com/assets/841141/17079431/3a872fe8-50de-11e6-89b9-83188e8e6956.png)

**Comment by asyven** [comment]
must have?

**Comment by Novalys** [comment]
Yes, it's a must have because of the features we are using (.Net Framework 4.5)
