### ISSUE TITLE
Add the Navigation System from Rocket API

### ISSUE THREAD

**Issue by Novalys** [Novalys/PokemonGo-Bot-SimpleGUI#5]
There is a system in the Rocket API to calculate the distance between two points (current location and next pokestop) and depending on that distance use a different delay (to simulate walking).

**Comment by sigboe** [comment]
Does the bot also hatch eggs? I'm asking this here, because I feel like that would also be a use for the navigation system.

**Comment by Khayalan** [comment]
Sounds awesome ^^ Hopefully the bot can then now hatch eggs :+1: 
I hope you implement this soon
