### ISSUE TITLE
Move crash logs to a new directory

### ISSUE THREAD

**Issue by darkhax** [Novalys/PokemonGo-Bot-SimpleGUI#50]
Currently crash logs are generated in the app directory, and over time clutter it up. It would be cleaner to move these to a sub-directory. It may also be beneficial to move to a user friendly file naming for the date the file was created.

**Comment by Novalys** [comment]
@darkhax Indeed, also I want to write something to limite the amount of "retries" after a crash since most likely after 3 the application won't recover (at least now, until I find what is the real cause).
