### ISSUE TITLE
wondering if its possible for you to add a tick box that uses lucky eggs and incense?

### ISSUE THREAD

**Issue by dynamo21uk** [Novalys/PokemonGo-Bot-SimpleGUI#51]
wondering if its possible for you to add a tick box that uses lucky eggs and incense? every 30minutes or something?

ABSOLUTELY awesome bot btw.

**Comment by Novalys** [comment]
First of all thanks for the feedback, currently it seems that using lucky eggs and incense cause instant soft ban, but as soon as this is sorted out I'll add the feature! Thanks.
