### ISSUE TITLE
[NOTICE] I WILL BE OUT FOR THE WEEKEND 

### ISSUE THREAD

**Issue by Novalys** [Novalys/PokemonGo-Bot-SimpleGUI#53]
Hello guys, since I don't have any other way to communicate with you I just wanted to give a quick notice that I'll be out of town for the weekend so work will be stalled until I get back. In the mean time report any issue you find and I'll address every issue personally.

**Comment by UncleMart** [comment]
Thanks for the heads up :) I just want to say im impressed with what youve done so far and that i love your organization here and your super friendly and helpful attitude :)

I'll be hanging around trying to help where i can :) have an awesome weekend good sir!

**Comment by nxy** [comment]
Enjoy your weekend! Stay safe and have fun! You deserve it.

**Comment by wygasmateusz** [comment]
Yeach great app ! :+1:

**Comment by Delko0** [comment]
Hello great app! Could you possibly fix the annoying crash bug? If its not 2 hard to fix :+1:

**Comment by Wyn10** [comment]
@Novalys [If it helps you out I cherry-picked all the pull requests for easy forking....If there's something wrong with it disregard it](https://github.com/Wyn10/PokemonGo-Bot-SimpleGUI/commit/eaf669d1ed81d54f4f99ccf72ea202cbf13fc2db)  :+1: .

**Comment by smholsen** [comment]
Enjoy your weekend, Ill try to contribute and address some of the issues when I get time :)
