### ISSUE TITLE
No transferring pokemon when catching pokemon

### ISSUE THREAD

**Issue by nxy** [Novalys/PokemonGo-Bot-SimpleGUI#54]
The bot shouldn't be transferring pokemon while it's in the process of catching pokemon, which should reduce the chances of detection? I think..

**Comment by Mineroboter** [comment]
The bot doesn't transfer pokemon while he is catching pokemon. He only transfer when you manually transfer when the bot is not farming. Or if the bot went to all pokestops he analysed before, but even then he didn't catch pokemon.
