### ISSUE TITLE
Pokemon storage space

### ISSUE THREAD

**Issue by tyfn61** [Novalys/PokemonGo-Bot-SimpleGUI#57]
I bought pokemon storage space so i can storage 300 pokemon but the bot stops at 250 can u fix this pls :)

**Comment by nxy** [comment]
Yes, this bug has already been confirmed and will be fixed when he comes back from his trip.

**Comment by Novalys** [comment]
Correct, this is a duplicate and it's already being tracked in another issue, thanks for reporting anyways!
