### ISSUE TITLE
PTC login not saving details?

### ISSUE THREAD

**Issue by UncleMart** [Novalys/PokemonGo-Bot-SimpleGUI#60]
I'm unsure why, but I have to enter my details for the PTC every time I start the bot. I see the bot saves the user/pass in the /users/ directory but it also has the last used GPS and seems to be able to retrieve this ok.

Bug or intentional?

**Comment by Mineroboter** [comment]
Because the username and password aren't loaded into the LoginForm. I can't say why this was did.

**Comment by nxy** [comment]
>             // 
            // boxUsername
            // 
            this.boxUsername.Location = new System.Drawing.Point(72, 12);
            this.boxUsername.Name = "boxUsername";
            this.boxUsername.Size = new System.Drawing.Size(161, 20);
            this.boxUsername.TabIndex = 0;
            this.boxUsername.Text = UserSettings.Default.PtcUsername;
            this.boxUsername.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // boxPassword
            // 
            this.boxPassword.Location = new System.Drawing.Point(72, 38);
            this.boxPassword.Name = "boxPassword";
            this.boxPassword.PasswordChar = '*';
            this.boxPassword.Size = new System.Drawing.Size(161, 20);
            this.boxPassword.TabIndex = 1;
            this.boxPassword.Text = UserSettings.Default.PtcPassword;
            this.boxPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.boxPassword.KeyDown += new System.Windows.Forms.KeyEventHandler(this.boxPassword_KeyDown);

Here's a quick fix by editing PokemonGo.RocketAPI.GUI\LoginForm.cs\LoginForm.Designer.cs

**Comment by Novalys** [comment]
That is correct, the bot isn't meant to remember credentials but if you really need that feature the above fix will work just the way you expect. Thank you
