### ISSUE TITLE
recycled 192 pokeballs? broken bag upgrades and rasberry overuse

### ISSUE THREAD

**Issue by AliAlhabib** [Novalys/PokemonGo-Bot-SimpleGUI#62]
Hey! first of all thank you for this wonderful bot.

My tiny problem was that the bot did not recognize my storage space and pokemon storage as well, so it has recycled almost all of my items including 192 pokeballs

Edit: It is overusing rasberry, for example on low level geodudes, is there a way to be picky a bit this? or to let it stop using them for good?

Thank you once again, awesome work and very simplified!

**Comment by nxy** [comment]
The storage bugs will be fixed when he comes back from his trip. As for the berry, berries are used when the pokemon's capture probability is below 40%. For a quick fix, you could always change the value in the code by editing "PokemonGo.RocketAPI.GUI\MainForm.cs" for function ExecuteCatchAllNearbyPokemons()

                    if (encounterPokemonResponse?.CaptureProbability.CaptureProbability_.First() < 0.4)
                    {
                        //Throw berry is we can
                        await UseBerry(pokemon.EncounterId, pokemon.SpawnpointId);
                    }

**Comment by AliAlhabib** [comment]
hey! That's great news.

I honestly cannot find that file maybe because I don't have it?

This is what I have downloaded: 
https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/releases/download/v0.11-beta/PoGo-SimpleGUI_v0.11.Beta.zip

Could you please put in info on which file has the (stop farm, evolve). I wish for it to stop auto evolving as well that would be great!

Thank you for your help.

**Comment by nxy** [comment]
You'd have to use "The Advanced" directions in the readme file.

The Advanced

- Download Visual Studio 2015.
- Clone this Repository.
- Open the Pokemon Go Rocket API.sln (VS Solution File)
- On the Solution Explorer Menu right click "Pokemon.Go.RocketAPI.GUI" and select "Set as Startup Project"
- Press F5
- Enter your credentials, select your starting location from the map and start farming.

I believe that's the only way to customize the files and run them. When you're all setup, I'll tell you how to stop the auto evolving.

**Comment by AliAlhabib** [comment]
I thought so, it's being downloaded at the moment. hey thanks for doing this!

**Comment by nxy** [comment]
- Quick fix for stopping the auto evolving

"PokemonGo.RocketAPI.GUI\MainForm.cs" for function startBottingSession()

                try
                {
                    // Start Farming Pokestops/Pokemons.
                    await ExecuteFarmingPokestopsAndPokemons();

                    // Only Auto-Evolve/Transfer when Continuous.
                    if (isFarmingActive)
                    {
                        /*
                        // Evolve Pokemons.
                        btnEvolvePokemons_Click(null, null);
                        System.Threading.Thread.Sleep(10000);
                        */
                        // Transfer Duplicates.
                        btnTransferDuplicates_Click(null, null);
                        System.Threading.Thread.Sleep(10000);
                    }
                }

Make the edits, save the file, and press F5 to run.

**Comment by AliAlhabib** [comment]
Thanks boss! would this stop auto transfering as well?

I found Nova's software being sold on ebay: http://www.ebay.com/itm/Pokemon-GO-BOT-Roboter-automatisches-leveln-des-Accounts-lvl-25-/232024165606?hash=item3605b7cce6:g:nrYAAOSwhMFXk7cQ

a bit illegal isn't it?

**Comment by nxy** [comment]
If you tweak it a little bit, it can stop both auto evolving and transferring.

               try
                {
                    // Start Farming Pokestops/Pokemons.
                    await ExecuteFarmingPokestopsAndPokemons();

                    // Only Auto-Evolve/Transfer when Continuous.
                    if (isFarmingActive)
                    {
                        /*
                        // Evolve Pokemons.
                        btnEvolvePokemons_Click(null, null);
                        System.Threading.Thread.Sleep(10000);
                        
                        // Transfer Duplicates.
                        btnTransferDuplicates_Click(null, null);
                        System.Threading.Thread.Sleep(10000);
                        */
                    }
                }

Yes that's screwed up if it's not Nova....

**Comment by AliAlhabib** [comment]
already reported, don't think it's him at all.

Thank you, Visual studio is taking quiet a while haha. Appreciate all your help buddy

**Comment by Mineroboter** [comment]
If your item count for that item is higher than the following, the items will be sold to this point:
new KeyValuePair<ItemId, int>(ItemId.ItemUnknown, 0);
new KeyValuePair<ItemId, int>(ItemId.ItemPokeBall, 20);
new KeyValuePair<ItemId, int>(ItemId.ItemGreatBall, 20);
new KeyValuePair<ItemId, int>(ItemId.ItemUltraBall, 50);
new KeyValuePair<ItemId, int>(ItemId.ItemMasterBall, 100);
new KeyValuePair<ItemId, int>(ItemId.ItemPotion, 0);
new KeyValuePair<ItemId, int>(ItemId.ItemSuperPotion, 0);
new KeyValuePair<ItemId, int>(ItemId.ItemHyperPotion, 20);
new KeyValuePair<ItemId, int>(ItemId.ItemMaxPotion, 50);
new KeyValuePair<ItemId, int>(ItemId.ItemRevive, 10);
new KeyValuePair<ItemId, int>(ItemId.ItemMaxRevive, 50);
new KeyValuePair<ItemId, int>(ItemId.ItemLuckyEgg, 200);
new KeyValuePair<ItemId, int>(ItemId.ItemIncenseOrdinary, 100);
new KeyValuePair<ItemId, int>(ItemId.ItemIncenseSpicy, 100);
new KeyValuePair<ItemId, int>(ItemId.ItemIncenseCool, 100);
new KeyValuePair<ItemId, int>(ItemId.ItemIncenseFloral, 100);
new KeyValuePair<ItemId, int>(ItemId.ItemTroyDisk, 100);
new KeyValuePair<ItemId, int>(ItemId.ItemXAttack, 100);
new KeyValuePair<ItemId, int>(ItemId.ItemXDefense, 100);
new KeyValuePair<ItemId, int>(ItemId.ItemXMiracle, 100);
new KeyValuePair<ItemId, int>(ItemId.ItemRazzBerry, 200);
new KeyValuePair<ItemId, int>(ItemId.ItemBlukBerry, 10);
new KeyValuePair<ItemId, int>(ItemId.ItemNanabBerry, 10);
new KeyValuePair<ItemId, int>(ItemId.ItemWeparBerry, 30);
new KeyValuePair<ItemId, int>(ItemId.ItemPinapBerry, 30);
new KeyValuePair<ItemId, int>(ItemId.ItemSpecialCamera, 100);
new KeyValuePair<ItemId, int>(ItemId.ItemIncubatorBasicUnlimited, 100);
new KeyValuePair<ItemId, int>(ItemId.ItemIncubatorBasic, 100);
new KeyValuePair<ItemId, int>(ItemId.ItemPokemonStorageUpgrade, 100);
new KeyValuePair<ItemId, int>(ItemId.ItemItemStorageUpgrade, 100);

**Comment by AliAlhabib** [comment]
ahh, thank you. kinda sucks since I pay for those.

[22:29:58] Unable to Start Farming: You need to have free space for Items.
[22:30:01] Recycling Items to Free Space
[22:30:01] Requesting GetInventoryResponse
[22:30:01] Requesting RecycleInventoryItemResponse
[22:30:02] Recycled 64x ItemRevive
[22:30:02] Requesting RecycleInventoryItemResponse
[22:30:03] Recycled 192x ItemPokeBall
[22:30:03] Requesting RecycleInventoryItemResponse
[22:30:04] Recycled 34x ItemPotion
[22:30:04] Requesting RecycleInventoryItemResponse
[22:30:05] Recycled 47x ItemSuperPotion
[22:30:05] Requesting RecycleInventoryItemResponse
[22:30:06] Recycled 42x ItemHyperPotion
[22:30:06] Recycling Complete.

**Comment by Mineroboter** [comment]
But you don't need more items than that because the bot goes to pokestops.

**Comment by AliAlhabib** [comment]
Got visuals downloaded, not sure what repository I have to clone

**Comment by Mineroboter** [comment]
Go to https://github.com/Novalys/PokemonGo-Bot-SimpleGUI and download the zip file and extract it to C:\Users\USER\Documents\Visual Studio 2015\Projects

**Comment by AliAlhabib** [comment]
Alrighty thats done!

**Comment by AliAlhabib** [comment]
I have gotten to the point where I opened mainform.cs and right clicked start farming to view code.

**Comment by AliAlhabib** [comment]
if (encounterPokemonResponse?.CaptureProbability.CaptureProbability_.First() < 0.1) 
that's done I think

**Comment by AliAlhabib** [comment]
` try
                {
                    // Start Farming Pokestops/Pokemons.
                    await ExecuteFarmingPokestopsAndPokemons();

                    // Only Auto-Evolve/Transfer when Continuous.
                    if (isFarmingActive)
                    {
                        // Evolve Pokemons.
                        btnEvolvePokemons_Click(null, null);
                        System.Threading.Thread.Sleep(10000);

                        // Transfer Duplicates.
                        btnTransferDuplicates_Click(null, null);
                        System.Threading.Thread.Sleep(10000);`

This looks just like what you posted, what tweaks have to be made here. the only difference is in the /* you had :D

**Comment by AliAlhabib** [comment]
I have fixed my inventory lol! 

            // Write to Console
            Logger.Write($"Items in Bag: {myItems.Select(i => i.Count).Sum()}/750.");
            Logger.Write($"Pokemons in Bag: {myPokemons.Count()}/350.");

            // Checker for Inventory
            if (myItems.Select(i => i.Count).Sum() >= 750)
            {
                Logger.Write("Unable to Start Farming: You need to have free space for Items.");
                return false;
            }

            // Checker for Pokemons
            if (myPokemons.Count() >= 341) // Eggs are Included in the total count (9/9)
            {
                Logger.Write("Unable to Start Farming: You need to have free space for Pokemons.");
                return false;

**Comment by Mineroboter** [comment]
Do "/*" before "// Evolve Pokemons." and a "*/" after "Sleep(10000);" and before "// Transfer Duplicates."

**Comment by AliAlhabib** [comment]
That's done! thank you very much both of you!

**Comment by nxy** [comment]
Well done. :)

**Comment by Novalys** [comment]
Again, it's amazing to see you guys working the problems together, thanks!! Regarding the eBay sale... It's a shame since this is an open source project and all the development done is only to benefit everyone, I already got some messages of people selling it on forums and other places, but well... nothing we can do about it.
