### ISSUE TITLE
Inventory Full Results in Constant Crashes until you re-open

### ISSUE THREAD

**Issue by frostyshield** [Novalys/PokemonGo-Bot-SimpleGUI#64]
When your inventory becomes full the application can't handle it and results in crashing and resolving the issue requires you to either close or force close the application and repoen then recycle items before starting.

There needs to be more options in this program as well as a auto-recycle method to prevent app-crashes.

**Comment by Novalys** [comment]
Noted and added in issue #67 ! Thank you for the report.
