### ISSUE TITLE
Feature: Auto transfer pokemons/icons

### ISSUE THREAD

**Issue by alecstheone** [Novalys/PokemonGo-Bot-SimpleGUI#66]
It would be really nice a feature to auto transfer pokemons / icons when the storage is full. So you don't need to check every time if the storage is fulll or not.

Many thanks!

**Comment by Mineroboter** [comment]
I'm working on that. I'll create a pull request tomorrow. Hopefully :)

**Comment by Mineroboter** [comment]
https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/pull/68

**Comment by alecstheone** [comment]
Thanks alot!
Now there only the biggest issue left, namely that the bot stops working after a few minutes, the bih error that all the people are facing it :)

**Comment by Novalys** [comment]
Great let me quickly review the pull request to merge into the main branch, thanks a lot for the work!
