### ISSUE TITLE
[Settings View] Settings Summary

### ISSUE THREAD

**Issue by Mineroboter** [Novalys/PokemonGo-Bot-SimpleGUI#67]
I would welcome a SettingsForm for the following:
-Keep pokemons that can Evolve (just move it to the settings form)
-(Dis)enable auto evolve #43 
-White/Blacklist of pokemons which should/shouldn't be evolved #44 
-White/Blacklist of pokemons which should/shouldn't be transferred
-Custom item recycle settings https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/pull/68#issuecomment-234763304
-(Dis)enable auto transfer #34 
-Custom Item Inventory size 
-Custom Pokemon inventory size #57
-Change timer tick speed #39
-(Dis)enable auto incubating eggs (after implementation) #58 
-(Dis)enable auto recycling at full item inventory while farming
-(Dis)enable auto transferring at full pokemon inventory while farming

Reading #34 I saw that you are also planning this. (So see this as a summary :) ) Maybe I will write tomorrow some code snippets. (EDIT: No, I didn't :) )

**Comment by Novalys** [comment]
Yes, the Settings UI is definitely coming in the next release, thank you for summarizing most of the settings it will contain!
