### ISSUE TITLE
Thousands of Crash Logs

### ISSUE THREAD

**Issue by PassiveModding** [Novalys/PokemonGo-Bot-SimpleGUI#69]
After leaving home for a few hours I came back to almost 3000 crash logs. After the crash in the log box(in gui) it shows bot has crashed restarting in 5 seconds etc. however it will continue to do this infinitely. It would be helpful to even just have a singular crash log file or a folder where they go rather than the main directory to avoid clutter

**Comment by Wyn10** [comment]
#42

**Comment by PassiveModding** [comment]
Closed and continues on #42
