### ISSUE TITLE
"Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by mich3lam** [Novalys/PokemonGo-Bot-SimpleGUI#7]
Hey!
I was wondering when : ""Object reference not set to an instance of an object"" this happens it should restart the bot instead of stopping it.

                Logger.Write(ex.Message);
                btnStopFarming_Click(null, null);
                Logger.Write("Restarting the bot, a problem was found.");
                btnStartFarming_Click(null, null);

is this right?

**Comment by mich3lam** [comment]
btw. cant i do this if i want the start to recycle/remove duplicate/and farm?
            sessionTimer.Interval = 5000;
            sessionTimer.Start();
            sessionStartTime = DateTime.Now;

            try {
                // Start Farming Pokestops/Pokemons.
                await ExecuteFarmingPokestopsAndPokemons();
                await RecycleItems();
                await TransferDuplicatePokemon(cbKeepPkToEvolve.Checked);
            }
doesnt seem to work :(

**Comment by Novalys** [comment]
Ohh do you want like a "continuous farming" option? To just never stop and keep repeating? I can add a checkbox for that, sounds good?

**Comment by mich3lam** [comment]
well, a checkbox is ok i guess but i managed to do it :P 
i added lots of things but i need to figure out how i work with github and i can push it

**Comment by mich3lam** [comment]
@Novalys also fixed the check inv bug.. i'll try and figure out how to push it now.
https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/issues/2
but this must be added haha , that one is high priority! :D

**Comment by Novalys** [comment]
The inventory bug you mean the one that crashes the farming bot if your pokemons are full or inventory is full? I already have that fixed will try to push that along with #2 today.

**Comment by mich3lam** [comment]
ye that one. also
                if (!isFarmingActive)
                {
                    Logger.Write("CRITICAL ERROR. RESTARTING BOT.");
                    return;
                }         
in lines 520-524 stops the bot for no reason. needs to be removed

**Comment by onlylove943** [comment]
Recycle items function delete all items in invetory include Pokeball :-1:

**Comment by mich3lam** [comment]
@onlylove943 it makes sure u still have enough pokeballs to work with. thats the function lol

**Comment by onlylove943** [comment]
@mich3lam So how about other items like Egg or Incent?

**Comment by mich3lam** [comment]
@onlylove943 it doesnt touch these... it recycled greatballs and pokeballs and farms ultraballs

**Comment by onlylove943** [comment]
@mich3lam Thx for information. I was freak out when i saw it recycle my pokeballs lol

**Comment by Novalys** [comment]
There is a item list in the Settings file (https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/blob/master/PokemonGo.RocketAPI.GUI/Settings.cs) where you can write which items and how many of those to keep, currently it's set to a very usable amount for each but you can tweak as necessary.

**Comment by mich3lam** [comment]
@Novalys any idea why sometimes it stops the bot for no reason if there are no pokemons to catch? i can only connect it to lines 520 ~ 524 but that doesnt seem like the problem

**Comment by mich3lam** [comment]
@Novalys oh and when are u pushing #2

**Comment by onlylove943** [comment]
I'm using pre-compiled version since i don't have VS here to compile it myself. And 1 request, can u add code so the bot can transfer duplicated pokemon right after catching a duplicated one?

**Comment by Novalys** [comment]
Sure @onlylove943 any ways the compiled version is a little outdated I'm planning to add all the features and bug fixes that I have pending today when I get to my apartment ( currently at work :-1: ) and I'll take a look at that @mich3lam but lines 520/524 are a stopping mechanism that shouldn't be the problem it's something else but I'll find out.

**Comment by mich3lam** [comment]
@Novalys true.. when u remove that you can stop farming.. welll. there is also stopping mechanism at lines 600~604.. take a look and let me know what u think

**Comment by onlylove943** [comment]
Oh and 1 thing i just found out. The CP sorting in GUI have problem, it only sorts first 2 digit, not whole number. Sorry for bad English :(
![capture1](https://cloud.githubusercontent.com/assets/20055460/17069144/3ba14d5a-507f-11e6-8a36-0cba8c302ec6.JPG)

**Comment by Novalys** [comment]
Could you raise a new issue for that onlylove?

**Comment by onlylove943** [comment]
I think it's not important, just note that so you can fix if you want :D

**Comment by mich3lam** [comment]
@onlylove943 it is important.. things need to be addressed :) made the issue

**Comment by Novalys** [comment]
Exactly, might not be high-priority but a fix is a fix! :smile:

**Comment by Novalys** [comment]
Will close this as the issues reported here already have their own issue.
