### ISSUE TITLE
[SUGGESTIONS]

### ISSUE THREAD

**Issue by PassiveModding** [Novalys/PokemonGo-Bot-SimpleGUI#72]
Heres a large list of some suggestions I and a few others have thought of which would be very beneficial to the bot

- Evolve High CP first
- Choose inventory values eg. Recycle so the bot has 20 potions, 80 pokeballs, 40 great balls etc. (user defined)
- Walk To X eg. Having the option to change the location in which the bot is working without restarting and then having it just walk to the location (specify coordinates using the map same as on startup)
- Auto Lucky Egg on start
- Auto Hatch/Incubate
- Exclusion List for transferring (whitelist and blacklist)
- Protect High CP/IV pokemon from being transferred
- Prioritise higher CP, IV and rarity pokemon, eg. the bot chooses to capture a Dragonite over a zubat
- Soft Ban Detection eg. the bot stops and logs out leaving a message saying "you've been soft banned at X time" this would be to stop the bot wasting pokeballs and razzberries
- Specify the area in which you want to stay eg. only stay within an 10km radius of the starting point
- Manually remove items if you choose to do so, eg. Click potions and a box will pop up saying "remove X/38" etc
- More bot stats eg. Run time, Pokestops spun in total, Distance travelled, pokemon evolved, pokemon transferred, distance left on eggs

Multiple of these have already been seen before but I have neither the time nor the energy to reference them all

**Comment by Novalys** [comment]
Great ideas and as you said most are already in the works, should have all of those added to the next release.
