### ISSUE TITLE
[Use Lucky Egg] Usage of the Lucky Egg while Farming

### ISSUE THREAD

**Issue by AliAlhabib** [Novalys/PokemonGo-Bot-SimpleGUI#73]
Has anyone besides the developer tried using a lucky egg while botting?

were you soft banned? If yes or no what was your run time and how often do you use it?

I have over 60 of them it would be a shame not to use them while botting.

Thank you!

**Comment by JordyGitHub** [comment]
I added a pull request that lets you use a lucky egg by pressing a button in the gui. I have tried it (twice) and was not (soft)banned.
However, in order to retrieve the lucky eggs, I had to open the account on my phone to get the level up bonussen.

**Comment by AliAlhabib** [comment]
I have tried many times to run your code plentiful times, it keeps saying this build has errors would you like to run the last successful build? 

any advice on how to get through this?

**Comment by JordyGitHub** [comment]
What error message are you receiving?

**Comment by AliAlhabib** [comment]
well, one problem I'm encountering right now is:

var useLuckyEgg = await client.UseItemExpBoost(ItemId.ItemLuckyEgg);

where "UseItemExpBoost" is not refrenced

**Comment by AliAlhabib** [comment]
line 720

**Comment by JordyGitHub** [comment]
If you look at https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/pull/63/commits/0ae916538b45606e563c4159a3cedebb2cd71f09 then search for PokemonGo.RocketAPI/Client.cs. There you see I added a new function called UseItemExpBoost.
Make sure you take over that change

**Comment by AliAlhabib** [comment]
it worked! thank you so much!

next I'm trying to get your evolve settings

**Comment by Novalys** [comment]
Nice to see that Lucky Eggs are working now, will add this feature to the main release as soon as possible, thank you!!

**Comment by Novalys** [comment]
This has been merged. Thanks!
