### ISSUE TITLE
Can't battle GYM-s

### ISSUE THREAD

**Issue by Delko0** [Novalys/PokemonGo-Bot-SimpleGUI#74]
Ok so after botting an account to level 21,i wanted to go to one gym and battle for it,but every time i tried it would just send me out of it as soon as the battle started,does anyone have a similar issue? please note that on my legit account i can battle with no problems

EDIT: to make it more detalied when the battle starts,i see my pokemon and the enemy and as soon as "GO" flashes on the screen it just sends me out

**Comment by Mineroboter** [comment]
Maybe you have a soft ban. Wait ~1/2 hours and then try again but don't use the bot while waiting

**Comment by Delko0** [comment]
Nope,i waited for around 10 hours and no soft bans ever

**Comment by UncleMart** [comment]
This can happen if you're on the edge of the gym area, it'll let you get right up to the fight but then kick you out. I had to walk quite far from the area and then go back and it worked again.

**Comment by Delko0** [comment]
@UncleMart Could be..ill try again on another gym tomorrow

**Comment by R1NZLR** [comment]
did the account you picked have a team? Because I botted one past team choice and now I cant battle with it

**Comment by Delko0** [comment]
@R1NZLR  Yeah it had a huge team or something,i could not edit it maybe it was bugged

**Comment by asyven** [comment]
Man, i have this trouble too. I botting in the next gym and this bu was fixed.

**Comment by Khayalan** [comment]
You can join a team if you are level 17 too for example just click on the gym :)

**Comment by Delko0** [comment]
@Khayalan Joining a gym is not a problem,please read again

**Comment by Novalys** [comment]
It seems this is not bot related so I will close it for now to avoid having misleading issues in the list, open a new one if you think this become relevant to the bot development, thank you!
