### ISSUE TITLE
Cant open the Source in Visual Studio 2015

### ISSUE THREAD

**Issue by EncepT** [Novalys/PokemonGo-Bot-SimpleGUI#76]
Hey im pretty new to the bot.
I wanted to look at the source and maybe switch some things but when i try to open the designer,it gives me an error.
an screenshot of the error is attached.
Thanks for help! :+1: 

[http://i.imgur.com/f9fiEdR.png](url)

**Comment by Mineroboter** [comment]
I had the same error. Make sure you have all NuGet-packets installed/up to date. (Project -> manage NuGet-packets) Then start the bot. Now the NuGet-packets will be loaded and after you closed the bot you wont the the error.

**Comment by EncepT** [comment]
@Mineroboter Can you might give me the url of the NuGet Packets you installed?
i tried that and it didnt help me out.
Thanks anyway!

**Comment by Mineroboter** [comment]
http://fs5.directupload.net/images/160724/epsektyd.png
If you haven't installed something, google for it and install that.

**Comment by Wyn10** [comment]
Follow the steps in the readme before editing anything.

**Comment by R1NZLR** [comment]
Team > Connections > Clone > insert URL

Open Solution, right click the solution in the solution explorer, select update nuget packages.

**Comment by EncepT** [comment]
Thanks its working now!
Appreciate that ! :)

**Comment by Novalys** [comment]
Great to hear is working for you and thanks to all the people that helped resolving this, you rock!
