### ISSUE TITLE
Hey Novalys

### ISSUE THREAD

**Issue by mich3lam** [Novalys/PokemonGo-Bot-SimpleGUI#78]
@Novalys 

Whenever you are back check my clone of Nekrobot:
https://github.com/mich3lam/NecroBot

-Added API changes they didn't add to Necro

It's updated to latest and I've added good things they do not want to add to the API. I have merged the GUI into it as much as I could but for some reason the login never worked and probably didn't change other things. The one on my Github is fully working with 0 crashes. If that can be merged into the GUI you made it would be amazing! :) Have a great day!

**Comment by Novalys** [comment]
So to understand this, you basically grabbed the latest Necro's and added extra stuff right? Could you tell me what big changes were made in Necro's and what extra stuff was added? (So I can skip looking into all that was made during the weekend)?

**Comment by mich3lam** [comment]
@Novalys what I can do is change everything I CAN figure inside the MainForm.cs to to adopt to the new changes in the Necro thingy, and then I can send you a link and maybe you can see what I keep ruining the login thingy .. if that's fixed it would have be update fully to Necro thingy. should I do that?

**Comment by Novalys** [comment]
What we can do to make it easier on you is if you can help me adding all the latest features from the Necro's outside the GUI project and I can just go ahead and use those functions from the Logic project (if they are still doing it that way) so we don't duplicate efforts on the GUI, what do you think?

**Comment by mich3lam** [comment]
@Novalys look at necros, it's whole different thing now :| they changed everything lol

**Comment by mich3lam** [comment]
@Novalys Oh god. Everytime I want to work I see they changed the whole thing again.... :|

**Comment by Novalys** [comment]
@mich3lam Yeah, I see they are just pushing to add new stuff and they don't care at all if they change the whole project upside down, I guess from this point it's better if we just stick to what we have and improve it from there.

**Comment by mich3lam** [comment]
@Novalys maybe we should update to the latest one and just stick to it? because it fixes many things and changes logics to new ones which are better.. what do u think ?

**Comment by Novalys** [comment]
@mich3lam I think for now I'm going to just maintain this code base as I really don't have much time, the first weekend I get free I'll try to catch up with Necro's :smile:
