### ISSUE TITLE
No issues - just a comment really

### ISSUE THREAD

**Issue by yupdon** [Novalys/PokemonGo-Bot-SimpleGUI#79]
Added Keep atleast Pokemon amount - on local version if liked I can commit.

Also changed all waiting time to random number between 10 and 20 seconds.

![image](https://cloud.githubusercontent.com/assets/8333350/17104158/468f099a-5247-11e6-8d31-107f0490c3ff.png)

**Comment by mich3lam** [comment]
@yupdon i've added bunch of things to the gui but the crashing drives me crazy. were u able to fix the exception errors?

**Comment by yupdon** [comment]
@mich3lam Not the ones that occur after hours of use. Currently mine works for at least 2- 3 hours at a time. - However this is a separate ticket, btw are you working with an older version? ("bunch of things to the gui") - don't answer here - open a ticket for it, or comment on the an existing ticket for this issue - thanks!

**Comment by Novalys** [comment]
Hello guys, I'm going to catch up with the development today after the weekend out. Will be mostly focusing in the "after hours crash bug" and will try to include all the requested features as possible. Will close this for now as the option to change the amount of Pokemon to keep and the delay time will be added a setting in a custom view.
