### ISSUE TITLE
Committed code..

### ISSUE THREAD

**Issue by yupdon** [Novalys/PokemonGo-Bot-SimpleGUI#83]
Hey tried to upgrade your app a bit, if you could find where it wen't - new to github. Sorry if I caused you a hassle, notes should be in the Push.

**Comment by yupdon** [comment]
Ah nvm -  Failed to push to the remote repository. See the Output window for more details.
Error encountered while pushing to the remote repository: Response status code does not indicate success: 403 (Forbidden).

This is what I changed: let me know if you want / how to add this:
Added boxPokemonCP to Fighting Pokemon group box.
Fixed mispelling in cbKeepPkToEvolve from "Keep Pokemons that can Evolve" to "Keep Pokemon that can Evolve".
Added Keep amount to increase duplicates kept.
Added CP threashold for Transfer Duplicates.

**Comment by PassiveModding** [comment]
definitely those last two need to be added

**Comment by Novalys** [comment]
Those features are added! :smile:
