### ISSUE TITLE
[23:31:33] Transfer Eevee with 745 CP 

### ISSUE THREAD

**Issue by PassiveModding** [Novalys/PokemonGo-Bot-SimpleGUI#84]
I was looking through the logs when bam "[23:31:33] Transfer Eevee with 745 CP" this almost made me cry haha
I think the issue with transferring high IV and CP pokemon needs to be addressed and fixed soon
or the implementation of more settings where you can turn off these sorts of things

**Comment by tyfn61** [comment]
Yes it should be fix soon :( btw i guess snorlax, dragonite and i suppose some other pokemons dont get transferred does any1 know which pokes dont get transsferred ?

**Comment by Novalys** [comment]
This has been fixed in the latest release.
