### ISSUE TITLE
UNSOFTBAN FEATURE

### ISSUE THREAD

**Issue by asyven** [Novalys/PokemonGo-Bot-SimpleGUI#86]
http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/564348-get-unbanned-if-you-have-softban-going.html 

Need add feature for using poketstop 40 times

sry 4 bad english

**Comment by KortakNL** [comment]
:)

I jumped from netherlands, europe to Santa monica, California and was soft banned.

Turned on the bot..
0 XP
pokemon ran way

after 14 pokemon ranaway and 9 pokestops (7 min had passed)

50xp
catched pokemon

so this works...:)

ate my lucky egg and farmin USA now (from europe)

nice find...

**Comment by KortakNL** [comment]
could also be a trap
maybe this is niantic figuring out who is using bots or not...?

**Comment by Novalys** [comment]
Could be, but it seems is working for multiple people in the forum, I'm going to soft ban an alt account I have and if it works I'll add it as an option with a warning sign that this isn't completely verified.

**Comment by Novalys** [comment]
It seems that leaving the bot farming will also works.
