### ISSUE TITLE
Time between pokemon and pokestops

### ISSUE THREAD

**Issue by yupdon** [Novalys/PokemonGo-Bot-SimpleGUI#87]
I found that when I changed the code to catch or moveNext to a random number between (10k and 20k) I don't get softbanned in locations with very few pokestops. - I think this is worth looking into!

I'm wondering if we can / should do a count of available pokestops in the area, and devide the pokestop next step by 5 minutes ( the time it takes to refresh ?)

**Comment by Novalys** [comment]
Adding a random delay is part of the work being done for the next release, I'll do some testing regarding the amount of pokestops and the relation with the delay to see if I can recreate this and come up with a formula that mitigates soft ban risk. Thanks for the report!

**Comment by Novalys** [comment]
You can know change the delay in the settings view, let me know if that works for you!
