### ISSUE TITLE
Literally everything is running away

### ISSUE THREAD

**Issue by alucard0134** [Novalys/PokemonGo-Bot-SimpleGUI#9]
Im not sure if this is something with the bot itself or Niantic tbh but everything including low CP will just run away

https://a.cuntflaps.me/pwiza.png

**Comment by onlylove943** [comment]
You're softbanned. Wait about 1-12 hours and retry.

**Comment by alucard0134** [comment]
Ah thought so, Danke.

**Comment by Novalys** [comment]
Yes that is correct, try not to change drastically from locations, today I'm adding the Google Maps feature so it should be easier to select your initial location.
