### ISSUE TITLE
Pokemon keep running away

### ISSUE THREAD

**Issue by lrbachtiar** [Novalys/PokemonGo-Bot-SimpleGUI#91]
For some reason the bot cannot catch pokemon at all. See screenshot.

![screen shot 2016-07-27 at 9 05 51 am](https://cloud.githubusercontent.com/assets/15060554/17155555/b506370c-53d9-11e6-8d36-913c60484515.png)

**Comment by atemerino** [comment]
You're softbanned, wait for 2 hours and try again.

**Comment by Versified** [comment]
You are softbanned which can last from 5 to 8 hours. Usually only takes a few minutes. You must've been teleporting around.

**Comment by Novalys** [comment]
As the others said, you are soft banned, you can find more information on the main page of the project about that, but overall don't worry just give it some time and you'll be back catching Pokemon.

**Comment by lrbachtiar** [comment]
Thanks for the response guys! I wasn't sure if I was soft-banned because this happened as soon as I started the app. But it looks all good now.

**Comment by KortakNL** [comment]
If you just keep it running you get un softbanned around 7 min or 22 pokestops+ pokemon

(did that 3x times already)
