### ISSUE TITLE
I have 650 bag items position。it just show 350 in the bot App

### ISSUE THREAD

**Issue by xtutu** [Novalys/PokemonGo-Bot-SimpleGUI#96]
i bought 300 bag items，so i have 350 + 300 item position...
but the application just limit at 350。。。

**Comment by Versified** [comment]
I can see the problem, I will work on a fix

**Comment by Versified** [comment]
`Logger.Write($"Items in Bag: {myItems.Select(i => i.Count).Sum()}/350");`

It's because the literal string is set to "Items in Bag: {how many items you have}/350"
Instead of: "Items in Bag: {how many you have}/{bag space}"

**Comment by Novalys** [comment]
Hey @Versified, I had this problem in my backlog list, indeed right now the program doesn't check for the inventory just assumes the default size but I haven't found time to dig into this. It would be awesome if you could retrieve the correct info from the server! Let me know if you want to do it?

**Comment by Versified** [comment]
@Novalys Yeah, I'm trying to rn, I'm just looking for someone who has inventory space who will help me check.
