### ISSUE TITLE
Can someone with inventory upgraded space test this?

### ISSUE THREAD

**Issue by Versified** [Novalys/PokemonGo-Bot-SimpleGUI#97]
If you have more inventory space can you test this for me:
In the MainForm.cs code goto line 230~ should see the method preflightCheck();

add 
`InventoryUpgrade up = new InventoryUpgrade();`

and add
`Logger.Write("TEST:" + up.CalculateSize());`

then run it and tell me the outcome.

The outcome will be somewhere in this box:
http://prntscr.com/by2ko9

**Comment by Novalys** [comment]
I'm afraid I don't have any extra inventory besides the default size, maybe someone else can test this?

**Comment by Versified** [comment]
Yeah still searching.

**Comment by Beltian** [comment]
I have upgraded inventory, was just about to post a bug report, it shows my inventory at 582/350 and wont let me start because i dont have space, when i have 750 slots.

**Comment by Versified** [comment]
Alright, thanks!

**Comment by Beltian** [comment]
Ok I have added those two lines, and It shows the TEST:0 in the log.
![2](https://cloud.githubusercontent.com/assets/4401166/17173053/1c035dc0-53be-11e6-86f2-1504768cfbc7.png)

![1](https://cloud.githubusercontent.com/assets/4401166/17173020/f6815d36-53bd-11e6-81eb-fdbe8ea38570.png)

**Comment by Versified** [comment]
Alright hold on.
I'm just trying to find out where it stores the information for extra slots.

**Comment by Beltian** [comment]
Ok, do you have discord? may be faster on that.

**Comment by Versified** [comment]
Meh, I can't figure it out :anguished:

**Comment by brutang** [comment]
As a hack, you can always have the user input a bag/pokemon size. That's only if you can't find it elsewhere.

**Comment by nxy** [comment]
Hi Beltian, if you could please add this code to "PokemonGo.RocketAPI.Logic" for Inventory.cs

        public async Task<IEnumerable<InventoryUpgrades>> GetInventoryUpgrades()
        {
            var inventory = await _client.GetInventory();
            return inventory.InventoryDelta.InventoryItems
                .Select(i => i.InventoryItemData?.InventoryUpgrades)
                .Where(p => p != null);
        }


Also "PokemonGo.RocketAPI.GUI\MainForm.cs" for preflightCheck()

            var myInventoryUpgrades = await inventory.GetInventoryUpgrades();

            var myUpgrades = myInventoryUpgrades.ToList();
            foreach (var upgrades in myUpgrades)
                Logger.Write($"Upgrades: {upgrades}");

This isn't a fix to your problem but it could lead to it. I just want to see the content of the InventoryUpgrades.

@Genaga Well.. one of the problems is that you can't start the bot if your total items is greater than your inventory space. I mean sure we could change it manually but I'd prefer "flexibility".

**Comment by Beltian** [comment]
Hey nxy, I tried adding your code, but it gives me an error.

![3](https://cloud.githubusercontent.com/assets/4401166/17190876/206a6ce2-540d-11e6-9326-576a6f70774c.png)

**Comment by nxy** [comment]
@Beltian Oops. I don't have the latest stuff. It should be

        var myInventoryUpgrades = await _inventory.GetInventoryUpgrades();

        var myUpgrades = myInventoryUpgrades.ToList();
        foreach (var upgrades in myUpgrades)
            Logger.Write($"Upgrades: {upgrades}");

**Comment by Beltian** [comment]
Ok that works. Here is the logger of it.

`[15:33:03] Requesting GetInventoryResponse
[15:33:03] Requesting GetInventoryResponse
[15:33:03] Requesting GetInventoryResponse
[15:33:03] Requesting GetInventoryResponse
[15:33:03] Requesting GetInventoryResponse
[15:33:04] Requesting GetInventoryResponse
[15:33:04] Upgrades: { "inventoryUpgrades": [ { "item": 1002, "upgradeType": "INCREASE_ITEM_STORAGE", "additionalStorage": 50 }, { "item": 1002, "upgradeType": "INCREASE_ITEM_STORAGE", "additionalStorage": 50 }, { "item": 1002, "upgradeType": "INCREASE_ITEM_STORAGE", "additionalStorage": 50 }, { "item": 1002, "upgradeType": "INCREASE_ITEM_STORAGE", "additionalStorage": 50 }, { "item": 1002, "upgradeType": "INCREASE_ITEM_STORAGE", "additionalStorage": 50 }, { "item": 1002, "upgradeType": "INCREASE_ITEM_STORAGE", "additionalStorage": 50 }, { "item": 1002, "upgradeType": "INCREASE_ITEM_STORAGE", "additionalStorage": 50 }, { "item": 1002, "upgradeType": "INCREASE_ITEM_STORAGE", "additionalStorage": 50 } ] }
[15:33:04] Items in Bag: 582/750.
[15:33:04] Lucky Eggs in Bag: 2
[15:33:04] Pokemons in Bag: 142/250.
[15:33:04] Unable to Start Farming: You need to have free space for Items.`

**Comment by nxy** [comment]
Ok.. This should work.

        private async Task<bool> PreflightCheck()
        {
            // Get Pokemons and Inventory
            var myItems = await _inventory.GetItems();
            var myPokemons = await _inventory.GetPokemons();
            var itemStorageUpgradesCount = await _inventory.GetItemAmountByType(MiscEnums.Item.ITEM_ITEM_STORAGE_UPGRADE);
            var pokemonStorageUpgradesCount = await _inventory.GetItemAmountByType(MiscEnums.Item.ITEM_POKEMON_STORAGE_UPGRADE);
            
            // Write to Console
            var items = myItems as IList<Item> ?? myItems.ToList();
            var pokemon = myPokemons as IList<PokemonData> ?? myPokemons.ToList();

	        Logger.Write($"Item Storage Size: {itemStorageSize}");
            Logger.Write($"Items in Bag: {items.Select(i => i.Count).Sum()}/{itemStorageSize}.");
            Logger.Write($"Lucky Eggs in Bag: {items.FirstOrDefault(p => (ItemId)p.Item_ == ItemId.ItemLuckyEgg)?.Count ?? 0 }");
            Logger.Write($"Pokemons in Bag: {pokemon.Count()}/250.");

            // Checker for Inventory
            if (items.Select(i => i.Count).Sum() >= itemStorageSize)
            {
                Logger.Write("Unable to Start Farming: You need to have free space for Items.");
                return false;
            }

            // Checker for Pokemons
            if (pokemon.Count() >= 241) // Eggs are Included in the total count (9/9)
            {
                Logger.Write("Unable to Start Farming: You need to have free space for Pokemons.");
                return false;
            }

            // Ready to Fly
            Logger.Write("Inventory and Pokemon Space, Ready.");
            return true;
}

**Comment by Beltian** [comment]
`The name itemStorageSize does not exist in the current context.`

**Comment by nxy** [comment]
Updated it. I forgot a variable. :p

**Comment by Beltian** [comment]
Ok that works, but still showing me only having 350 slots instead of the 750 i have.

**Comment by anton101101** [comment]
Will adding the above code by **nxy** to PokemonGo.RocketAPI.Logic get around the problem of the bot not starting?
Thanks

**Comment by Beltian** [comment]
If you want it to work for now until an official fix can be implemented do this:

find the following line in MainForm.cs
`// Checker for Inventory `

right below that should be a line that says

`if (items.Select(i => i.Count).Sum() >= 350)`

change the 350, to the amount of slots you have. then rebuild and you should be all set for now.

**Comment by nxy** [comment]
var myItemStorageUpgrades = await _inventory.GetInventoryUpgrades();

            var itemStorageUpgradesCount = myItemStorageUpgrades.FirstOrDefault(i => (MiscEnums.Item)i.InventoryUpgrades_ == MiscEnums.Item.ITEM_ITEM_STORAGE_UPGRADE)?.Count ?? 0;

The current problem is "(MiscEnums.Item)i.InventoryUpgrades_". I'm unable to convert to the correct type.

**Comment by Beltian** [comment]
is there a way to do a for loop for each item storage upgrade in the list, then have that set a variable to get the number of them?


```
i = 0;
foreach iteminlist(
i++
);

then do the math for 

invenSlots = i * 50 + 350;
```

something along those lines?

**Comment by nxy** [comment]
var myItemStorageUpgrades = await _inventory.GetInventoryUpgrades();
        var itemStorageUpgradesCount = myItemStorageUpgrades.Count();

**Comment by Beltian** [comment]
progress, i added that in, and it goes to 400. the response of the item storage upgrade count is now 1 instead of 0

**Comment by nxy** [comment]
I updated the code. The one above your comment.

**Comment by Beltian** [comment]
that change made it go back to 350

**Comment by nxy** [comment]
Can you show me what prints out of myItemStorageUpgrades.ToString()?

**Comment by nxy** [comment]
Ok I figured it out. I updated the code.

**Comment by Beltian** [comment]
works perfect! just need to change one thing,
```
        var myItemStorageUpgrades = await inventory.GetInventoryUpgrades();
        var itemStorageUpgradesCount = Regex.Matches(myItemStorageUpgrades.ToList()[0].ToString(), "1002").Count;
```

to 

```
        var myItemStorageUpgrades = await _inventory.GetInventoryUpgrades();
        var itemStorageUpgradesCount = Regex.Matches(myItemStorageUpgrades.ToList()[0].ToString(), "1002").Count;
```

**Comment by nxy** [comment]
Awesome!

        private async Task<bool> PreflightCheck()
        {
            var pokemonStorageUpgradesCount = 0;
            var itemStorageUpgradesCount = 0;

            // Get Pokemons and Inventory
            var myItems = await _inventory.GetItems();
            var myPokemons = await _inventory.GetPokemons();
            var myInventoryUpgrades = await _inventory.GetInventoryUpgrades();

            if (myInventoryUpgrades.Count() != 0)
            {
                var tmpInventoryUpgrades = myInventoryUpgrades.ToList()[0].ToString();
                pokemonStorageUpgradesCount = Regex.Matches(tmpInventoryUpgrades, "1001").Count;
                itemStorageUpgradesCount = Regex.Matches(tmpInventoryUpgrades, "1002").Count;
            }
            
            var pokemonStorageSize = (pokemonStorageUpgradesCount * 50) + 250;
            var itemStorageSize = (itemStorageUpgradesCount * 50) + 350;

            // Write to Console
            var items = myItems as IList<Item> ?? myItems.ToList();
            var pokemon = myPokemons as IList<PokemonData> ?? myPokemons.ToList();

            Logger.Write($"Items in Bag: {items.Select(i => i.Count).Sum()}/{itemStorageSize}.");
            Logger.Write($"Lucky Eggs in Bag: {items.FirstOrDefault(p => (ItemId)p.Item_ == ItemId.ItemLuckyEgg)?.Count ?? 0 }");
            Logger.Write($"Pokemons in Bag: {pokemon.Count()}/{pokemonStorageSize}.");

            // Checker for Inventory
            if (items.Select(i => i.Count).Sum() >= itemStorageSize)
            {
                Logger.Write("Unable to Start Farming: You need to have free space for Items.");
                return false;
            }

            // Checker for Pokemons
            if (pokemon.Count() >= pokemonStorageSize - 9) // Eggs are Included in the total count (9/9)
            {
                Logger.Write("Unable to Start Farming: You need to have free space for Pokemons.");
                return false;
            }

            // Ready to Fly
            Logger.Write("Inventory and Pokemon Space, Ready.");
            return true;
}

**Comment by anton101101** [comment]
Good job guys.

@Novalys can this go into the master

**Comment by Novalys** [comment]
YES, please create the pull request when it's ready! Awesome work guys! :smile:
